# Generated by Django 2.2.4 on 2020-01-07 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('companyImage', models.ImageField(blank=True, null=True, upload_to='referrerImages')),
            ],
            options={
                'ordering': ('companyName',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profileImages')),
                ('calendlyUrl', models.URLField(blank=True, null=True)),
                ('calendlyInterviewUrl', models.URLField(blank=True, null=True)),
                ('isHousehold', models.BooleanField(blank=True, default=False, null=True)),
                ('isCreditRep', models.BooleanField(blank=True, default=False, null=True)),
                ('isCapital', models.BooleanField(blank=True, default=False, null=True)),
                ('salesforceID', models.CharField(blank=True, max_length=18, null=True)),
                ('zoomID', models.CharField(blank=True, max_length=30, null=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Referer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
