# Generated by Django 2.1.7 on 2019-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isCapital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
