# Generated by Django 2.2.4 on 2019-12-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zoomID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
