# Generated by Django 2.1.7 on 2019-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_iscapital'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calendlyUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
