# Generated by Django 2.2.4 on 2020-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_referer_iscasereferrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='referer',
            name='companyUsername',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
