# Generated by Django 2.2.4 on 2020-04-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_referer_companyusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referer',
            name='companyUsername',
        ),
    ]
