# Generated by Django 2.2.4 on 2020-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200503_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='referenceUID',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
