# Generated by Django 2.2.4 on 2019-12-08 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('meetingName', models.CharField(blank=True, max_length=50, null=True)),
                ('calendlyID', models.CharField(blank=True, max_length=16, null=True)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('zoomID', models.CharField(blank=True, max_length=7, null=True)),
                ('customerName', models.CharField(blank=True, max_length=50, null=True)),
                ('customerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('customerPhone', models.CharField(blank=True, max_length=11, null=True)),
                ('enqUID', models.UUIDField(null=True)),
                ('caseUID', models.UUIDField(null=True)),
                ('isLive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
