# Generated by Django 2.2.4 on 2020-01-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendly',
            name='caseUID',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendly',
            name='enqUID',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
