# Generated by Django 2.2.4 on 2019-12-08 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendly',
            name='calendlyID',
            field=models.CharField(default="initial", max_length=16),
            preserve_default=False,
        ),
    ]
