# Generated by Django 2.2.4 on 2020-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0002_auto_20200111_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendly',
            name='zoomID',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
