# Generated by Django 2.2.4 on 2019-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0002_auto_20191208_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendly',
            name='timeZone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
