# Generated by Django 2.2.4 on 2019-12-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0003_calendly_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendly',
            old_name='isLive',
            new_name='isCalendlyLive',
        ),
        migrations.AddField(
            model_name='calendly',
            name='isZoomLive',
            field=models.BooleanField(default=True),
        ),
    ]
