# Generated by Django 2.2.4 on 2019-12-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0004_auto_20191210_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendly',
            name='isZoomLive',
            field=models.BooleanField(default=False),
        ),
    ]
