# Generated by Django 2.2.4 on 2020-09-26 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('productType', models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income'), (2, 'Combination'), (3, 'Contingency 20K')], default=0, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('loanType', models.BooleanField(default=True)),
                ('age_1', models.IntegerField()),
                ('age_2', models.IntegerField(blank=True, null=True)),
                ('dwellingType', models.BooleanField(default=True)),
                ('valuation', models.IntegerField()),
                ('streetAddress', models.CharField(blank=True, max_length=80, null=True)),
                ('suburb', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.IntegerField(blank=True, choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')], null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('maxLoanAmount', models.IntegerField(blank=True, null=True)),
                ('maxDrawdownAmount', models.IntegerField(blank=True, null=True)),
                ('maxDrawdownMonthly', models.IntegerField(blank=True, null=True)),
                ('maxLVR', models.FloatField(blank=True, null=True)),
                ('errorText', models.CharField(blank=True, max_length=40, null=True)),
                ('isTopUp', models.BooleanField(blank=True, null=True)),
                ('isRefi', models.BooleanField(blank=True, null=True)),
                ('isLive', models.BooleanField(blank=True, null=True)),
                ('isGive', models.BooleanField(blank=True, null=True)),
                ('isCare', models.BooleanField(blank=True, null=True)),
                ('calcLumpSum', models.IntegerField(blank=True, null=True)),
                ('calcIncome', models.IntegerField(blank=True, null=True)),
                ('application', models.BooleanField(default=False)),
                ('actioned', models.IntegerField(blank=True, default=0, null=True)),
                ('actionedBy', models.CharField(blank=True, max_length=40, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sourceID', models.CharField(blank=True, max_length=36, null=True)),
                ('calcTopUp', models.IntegerField(blank=True, null=True)),
                ('calcRefi', models.IntegerField(blank=True, null=True)),
                ('calcLive', models.IntegerField(blank=True, null=True)),
                ('calcGive', models.IntegerField(blank=True, null=True)),
                ('calcCare', models.IntegerField(blank=True, null=True)),
                ('calcTotal', models.IntegerField(blank=True, null=True)),
                ('payIntAmount', models.IntegerField(blank=True, null=True)),
                ('payIntPeriod', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('age_1', models.IntegerField(blank=True, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=1000)),
                ('actioned', models.IntegerField(blank=True, default=0, null=True)),
                ('actionNotes', models.CharField(blank=True, max_length=1000, null=True)),
                ('actionDate', models.DateField(blank=True, null=True)),
                ('sourceID', models.CharField(blank=True, max_length=36, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actionedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
