# Generated by Django 2.2 on 2019-04-30 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('loanType', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age_1', models.IntegerField()),
                ('age_2', models.IntegerField(blank=True, null=True)),
                ('dwellingType', models.BooleanField(default=True)),
                ('valuation', models.IntegerField()),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('maxLoanAmount', models.IntegerField(blank=True, null=True)),
                ('maxLVR', models.FloatField(blank=True, null=True)),
                ('errorText', models.CharField(blank=True, max_length=40, null=True)),
                ('isRefi', models.BooleanField(blank=True, default=False, null=True)),
                ('isTopUp', models.BooleanField(blank=True, default=False, null=True)),
                ('isLive', models.BooleanField(blank=True, default=False, null=True)),
                ('isGive', models.BooleanField(blank=True, default=False, null=True)),
                ('isCare', models.BooleanField(blank=True, default=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('actioned', models.IntegerField(blank=True, default=0, null=True)),
                ('actionedBy', models.CharField(blank=True, max_length=40, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('summaryDocument', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WebContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
