# Generated by Django 2.2.4 on 2020-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='mortgage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='repayment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income'), (2, 'Combination'), (3, 'Contingency 20K'), (4, 'Refinance')], default=0, null=True),
        ),
    ]
