# Generated by Django 2.1.7 on 2019-05-08 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='actionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='actionNotes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='actionedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
