# Generated by Django 2.2.4 on 2020-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcalculator',
            name='summaryDocument',
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='choiceMortgage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='choiceOtherNeeds',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='maxDrawdownAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='maxDrawdownMonthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='suburb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
