# Generated by Django 2.1.7 on 2019-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20190508_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='actioned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
