# Generated by Django 2.2.4 on 2020-10-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20201016_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcalculator',
            old_name='mortgage',
            new_name='mortgageDebt',
        ),
        migrations.RenameField(
            model_name='webcalculator',
            old_name='repayment',
            new_name='mortgageRepayment',
        ),
    ]
