# Generated by Django 2.1.7 on 2019-05-12 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_webcontact_actioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='contUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
