# Generated by Django 2.1.7 on 2019-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_webcontact_contuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='calcCare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcGive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcLive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcRefi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcTopUp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
