# Generated by Django 2.2.4 on 2020-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20200608_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Multi Purpose Lump Sum'), (1, 'Single Income'), (2, 'Single 20K')], default=0, null=True),
        ),
    ]
