# Generated by Django 2.2.4 on 2021-02-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20210107_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='base_specificity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='street_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='street_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
