# Generated by Django 2.2.4 on 2020-12-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20201230_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='firstname',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='lastname',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
