# Generated by Django 2.2.4 on 2020-12-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20201230_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcalculator',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='webcalculator',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='webcontact',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='webcontact',
            name='lastname',
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
