# Generated by Django 2.1.7 on 2019-06-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20190602_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcalculator',
            name='calcCare',
        ),
        migrations.RemoveField(
            model_name='webcalculator',
            name='calcGive',
        ),
        migrations.RemoveField(
            model_name='webcalculator',
            name='calcLive',
        ),
        migrations.RemoveField(
            model_name='webcalculator',
            name='calcRefi',
        ),
        migrations.RemoveField(
            model_name='webcalculator',
            name='calcTopUp',
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='isTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isCare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isGive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isLive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isRefi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isTopUp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
