# Generated by Django 2.2.4 on 2020-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20200616_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='application',
            field=models.BooleanField(default=False),
        ),
    ]
