# Generated by Django 2.2.4 on 2020-12-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20201230_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcalculator',
            name='name',
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='firstname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='lastname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
