# Generated by Django 2.2.4 on 2021-03-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_webcalculator_address_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcalculator',
            old_name='sourceID',
            new_name='origin_id',
        ),
    ]
