# Generated by Django 2.1.7 on 2019-06-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20190609_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcalculator',
            name='isTotal',
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcCare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcGive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcLive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcRefi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcTopUp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='calcTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isCare',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isGive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isLive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isRefi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webcalculator',
            name='isTopUp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
