# Generated by Django 2.1.7 on 2019-06-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_auto_20190609_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='payIntAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcalculator',
            name='payIntPeriod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
