# Generated by Django 2.2.4 on 2020-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_webcalculator_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
