# Generated by Django 2.2.4 on 2020-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_webcalculator_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='sourceID',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='age_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='sourceID',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
