# Generated by Django 2.2.4 on 2021-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20210313_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcalculator',
            name='origin_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webcontact',
            name='origin_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
