# Generated by Django 2.2.4 on 2021-03-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20210313_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontact',
            name='submissionOrigin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
