# Generated by Django 2.2.4 on 2021-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20210317_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webcontact',
            old_name='name',
            new_name='raw_name',
        ),
        migrations.RenameField(
            model_name='webcalculator',
            old_name='name',
            new_name='raw_name',
        ),
    ]
