# Generated by Django 2.2.4 on 2021-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_auto_20210318_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcontact',
            name='raw_name',
            field=models.CharField(max_length=256),
        ),
    ]
