# Generated by Django 2.2.4 on 2021-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_auto_20210318_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcalculator',
            name='submissionOrigin',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='webcontact',
            name='submissionOrigin',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
