# Generated by Django 2.2.4 on 2019-08-15 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('orgTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('orgType', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('orgType',),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('ordId', models.AutoField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(max_length=40, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('orgType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship.OrganisationType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('orgName',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('role', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.IntegerField(blank=True, choices=[(2, 'VIC'), (4, 'NSW'), (6, 'QLD'), (8, 'SA'), (10, 'WA'), (12, 'TAS'), (14, 'ACT'), (16, 'NT'), (20, 'FR'), (25, 'GE'), (30, 'HK'), (35, 'IR'), (40, 'JP'), (45, 'NZ'), (50, 'SG'), (55, 'UK'), (60, 'US')], null=True)),
                ('classification', models.IntegerField(blank=True, choices=[(2, 'Capital'), (4, 'Distribution'), (6, 'Investor'), (8, 'Product'), (10, 'Platform'), (12, 'Other')], null=True)),
                ('equityInterest', models.BooleanField(default=False)),
                ('debtInterest', models.BooleanField(default=False)),
                ('equityStatus', models.IntegerField(blank=True, choices=[(1, 'Need Contact'), (2, 'Email Sent'), (3, 'Meeting Scheduled'), (8, 'Meeting Held'), (10, 'Due Diligence'), (12, 'Confirmed'), (6, 'Declined'), (4, 'Inactive')], null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('relationshipNotes', models.TextField(blank=True, null=True)),
                ('relationshipOwners', models.CharField(blank=True, max_length=40, null=True)),
                ('inProfileUrl', models.URLField(blank=True, null=True)),
                ('inName', models.CharField(blank=True, max_length=40, null=True)),
                ('inDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('inPic', models.ImageField(blank=True, null=True, upload_to='relationshipImages')),
                ('inDate', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship.Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('surname',),
            },
        ),
    ]
