# Generated by Django 2.2.4 on 2019-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='requestNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
