# Generated by Django 2.1.7 on 2019-05-13 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('role', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.IntegerField(choices=[(2, 'VIC'), (4, 'NSW'), (6, 'QLD'), (8, 'SA'), (10, 'WA'), (12, 'TAS'), (14, 'ACT'), (16, 'NT'), (20, 'FR'), (25, 'GE'), (30, 'HK'), (35, 'IR'), (40, 'JP'), (45, 'NZ'), (50, 'SG'), (55, 'UK'), (60, 'US')])),
                ('classification', models.IntegerField(choices=[(2, 'Capital'), (4, 'Distribution'), (6, 'Investor'), (8, 'Product'), (10, 'Operations'), (12, 'Other')])),
                ('equityInterest', models.BooleanField(default=False)),
                ('debtInterest', models.BooleanField(default=False)),
                ('equityStatus', models.IntegerField(choices=[(2, 'Active'), (4, 'Inactive'), (6, 'Declined')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relationship.Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
