# Generated by Django 2.1.7 on 2019-05-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='relationshipNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
