# Generated by Django 2.1.7 on 2019-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_auto_20190513_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(2, 'Capital'), (4, 'Distribution'), (6, 'Investor'), (8, 'Product'), (10, 'Operations'), (12, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='equityStatus',
            field=models.IntegerField(blank=True, choices=[(2, 'Active'), (4, 'Inactive'), (6, 'Declined')], null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.IntegerField(blank=True, choices=[(2, 'VIC'), (4, 'NSW'), (6, 'QLD'), (8, 'SA'), (10, 'WA'), (12, 'TAS'), (14, 'ACT'), (16, 'NT'), (20, 'FR'), (25, 'GE'), (30, 'HK'), (35, 'IR'), (40, 'JP'), (45, 'NZ'), (50, 'SG'), (55, 'UK'), (60, 'US')], null=True),
        ),
    ]
