# Generated by Django 2.1.7 on 2019-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0004_auto_20190513_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='orgName',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
