# Generated by Django 2.1.7 on 2019-05-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0006_auto_20190513_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('surname',)},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('orgName',)},
        ),
        migrations.AlterModelOptions(
            name='organisationtype',
            options={'ordering': ('orgType',)},
        ),
    ]
