# Generated by Django 2.1.7 on 2019-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0007_auto_20190515_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='inDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='inDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='inName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='inPic',
            field=models.ImageField(blank=True, null=True, upload_to='relationshipImages'),
        ),
        migrations.AddField(
            model_name='contact',
            name='inProfileUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
