# Generated by Django 2.1.7 on 2019-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0008_auto_20190516_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
