# Generated by Django 2.1.7 on 2019-05-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0009_auto_20190517_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='relationshipOwners',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
