# Generated by Django 2.1.7 on 2019-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0010_contact_relationshipowners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(2, 'Capital'), (4, 'Distribution'), (6, 'Investor'), (8, 'Product'), (10, 'Platform'), (12, 'Other')], null=True),
        ),
    ]
