# Generated by Django 2.2.4 on 2021-02-03 05:44
import os 
from django.db import migrations
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.core.mail import mail_admins

from config.utils import set_settings

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    user, created = User.objects.get_or_create(
        username='integration_user'
    )
    token, created = Token.objects.get_or_create(user=user)
    if created: 
        set_settings('integration_user_token', token.key)
        mail_admins(
            'Client-App-{} Integration User - Token Created'.format(os.getenv('ENV', 'local')),
            'Integration user token reset to: {}'.format(token.key)
        )

def reverse_func(apps, schema_editor):
    Token.objects.filter(user__username='integration_user').delete()
    User.objects.filter(username='integration_user').delete()

    
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
