# Generated by Django 2.2.4 on 2021-03-23 02:40
from django.contrib.auth.models import User
from django.db import migrations

from apps.lib.api_Salesforce import apiSalesforce

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    user, created = User.objects.get_or_create(
        username='integration_user'
    )
    Profile = apps.get_model("accounts", "Profile")
    if not getattr(user, 'profile' ,None):
        sfAPI = apiSalesforce()
        sfAPI.openAPI(True)
        result = sfAPI.sf.query("Select Id from User where name='integration user'")
        if result['totalSize'] == 1: 
            salesforceID = result['records'][0]['Id']
        else:
            salesforceID = ''
        profile = Profile.objects.create(
            user_id=user.id,
            salesforceID=salesforceID
        ) 

def reverse_func(apps, schema_editor):
    user = User.objects.get(
        username='integration_user'
    )
    profile = getattr(user, 'profile' ,None)
    if profile:
        profile.delete()

    
class Migration(migrations.Migration):

    dependencies = [
        ('operational', '0001_integration_user'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
