# Generated by Django 2.1.7 on 2019-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='adviser',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
