# Generated by Django 2.2.4 on 2019-10-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundNotes', models.TextField(blank=True, null=True)),
                ('topUpNotes', models.TextField(blank=True, null=True)),
                ('refiNotes', models.TextField(blank=True, null=True)),
                ('liveNotes', models.TextField(blank=True, null=True)),
                ('giveNotes', models.TextField(blank=True, null=True)),
                ('careNotes', models.TextField(blank=True, null=True)),
                ('futureNotes', models.TextField(blank=True, null=True)),
                ('clientNotes', models.TextField(blank=True, null=True)),
                ('additionalNotes', models.TextField(blank=True, null=True)),
                ('homeQuestion', models.CharField(blank=True, max_length=20, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
            ],
        ),
    ]
