# Generated by Django 2.2.4 on 2019-10-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_factfind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factfind',
            name='homeQuestion',
        ),
        migrations.AddField(
            model_name='factfind',
            name='requirementsNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
