# Generated by Django 2.2.4 on 2020-02-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20200129_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsetting',
            name='investmentRate',
        ),
        migrations.RemoveField(
            model_name='modelsetting',
            name='projectionAge',
        ),
        migrations.AddField(
            model_name='modelsetting',
            name='establishmentFeeRate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
