# Generated by Django 2.2.4 on 2019-10-23 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20191021_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='factfind',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factfind',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
