# Generated by Django 2.2.4 on 2020-02-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20200211_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='newProcess',
        ),
    ]
