# Generated by Django 2.1.7 on 2019-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20190510_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='salesChannel',
            field=models.IntegerField(blank=True, choices=[(0, 'Independent Financial Advisers'), (1, 'Institutional Financial Advisers'), (2, 'Super Financial Advisers'), (3, 'Aged Care Advisers'), (4, 'Aged Care Provider/Consultants'), (5, 'Accountants'), (6, 'Centrelink Advisers'), (7, 'Brokers'), (8, 'Bank Referral'), (9, 'Refinance'), (10, 'Super Direct'), (11, 'Direct Acquisition')], null=True),
        ),
    ]
