# Generated by Django 2.1.7 on 2019-05-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20190515_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARN', models.CharField(blank=True, max_length=9, null=True)),
                ('advanced', models.FloatField(blank=True, default=0, null=True)),
                ('principal', models.FloatField(blank=True, default=0, null=True)),
                ('totalValuation', models.FloatField(blank=True, default=0, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
            ],
        ),
    ]
