# Generated by Django 2.2.4 on 2020-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20201016_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income'), (2, 'Combination'), (3, 'Contingency 20K'), (4, 'Refinance')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (6, 'TRANSPORT_AND_TRAVEL'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY')]),
        ),
    ]
