# Generated by Django 2.2.4 on 2019-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20191023_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='newProcess',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
