# Generated by Django 2.2.4 on 2020-02-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_case_newprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundeddata',
            name='application',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fundeddata',
            name='bPayCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fundeddata',
            name='bPayRef',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fundeddata',
            name='currentLVR',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fundeddata',
            name='dischargeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundeddata',
            name='settlementDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundeddata',
            name='totalValuation',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
