# Generated by Django 2.2.4 on 2020-02-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_auto_20200229_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactiondData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('transactionDate', models.DateTimeField()),
                ('effectiveDate', models.DateTimeField()),
                ('tranRef', models.FloatField(blank=True, default=0, null=True)),
                ('debitAmount', models.FloatField(blank=True, default=0, null=True)),
                ('creditAmount', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case.Case')),
            ],
            options={
                'verbose_name_plural': 'Transaction Data',
            },
        ),
    ]
