# Generated by Django 2.2.4 on 2019-11-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_case_newprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseType',
            field=models.IntegerField(choices=[(0, 'Discovery'), (2, 'Meeting Held'), (4, 'Application'), (5, 'Execution'), (6, 'Funded'), (3, 'Closed')]),
        ),
    ]
