# Generated by Django 2.1.7 on 2019-05-18 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_fundeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundeddata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundeddata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
