# Generated by Django 2.2.4 on 2020-02-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_transactionddata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactiondData',
            new_name='TransactionData',
        ),
    ]
