# Generated by Django 2.2.4 on 2020-12-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20201022_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (3, 'LIVE'), (4, 'GIVE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (6, 'TRANSPORT_AND_TRAVEL'), (7, 'LUMP_SUM'), (8, 'MORTGAGE')]),
        ),
    ]
