# Generated by Django 2.1.7 on 2019-05-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_auto_20190518_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='valuerEmail',
            field=models.EmailField(blank=True, choices=[('valuations@wbpgroup.com.au', 'valuations@wbpgroup.com.au'), ('instructions@opteonsolutions.com', 'instructions@opteonsolutions.com'), ('quotes@opteonsolutions.com', 'quotes@opteonsolutions.com')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='valuerFirm',
            field=models.CharField(blank=True, choices=[('WBP Group', 'WBP Group'), ('Opteon Solutions', 'Opteon Solutions')], max_length=20, null=True),
        ),
    ]
