# Generated by Django 2.2.4 on 2020-02-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20200229_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='effectiveDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='tranRef',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='transactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondata',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
