# Generated by Django 2.2.4 on 2019-11-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20191104_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='titleRequest',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='maritalStatus_1',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='maritalStatus_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed')], null=True),
        ),
    ]
