# Generated by Django 2.1.7 on 2019-06-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_auto_20190528_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='careDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='giveDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='renovateDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='travelDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
