# Generated by Django 2.2.4 on 2019-11-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20191107_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundeddata',
            name='ARN',
        ),
    ]
