# Generated by Django 2.2.4 on 2020-12-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20201222_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseDescription',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='case',
            name='firstname_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='firstname_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='middlename_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='middlename_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='preferredName_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='preferredName_2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='surname_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='surname_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
