# Generated by Django 2.2.4 on 2020-02-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20200229_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='tranRef',
            field=models.CharField(max_length=30),
        ),
    ]
