# Generated by Django 2.1.7 on 2019-06-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_auto_20190625_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='topUpDescription',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
