# Generated by Django 2.2.4 on 2019-11-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_remove_fundeddata_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='detailedTitle',
            field=models.BooleanField(default=False),
        ),
    ]
