# Generated by Django 2.1.7 on 2019-06-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_loan_topupdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='topUpFrequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='topUpIncomeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='topUpPeriod',
            field=models.IntegerField(default=0),
        ),
    ]
