# Generated by Django 2.2.4 on 2021-01-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_auto_20201229_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='factfind',
            name='additional_info_credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='all_applications_are_engaged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='applicant_poa_signing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='applicants_disengagement_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='considered_alt_downsizing_opts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='is_protected_equity',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='is_third_party_engaged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='is_vulnerable_customer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='plan_for_aged_care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='plan_for_future_giving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='planned_length_of_stay',
            field=models.IntegerField(blank=True, choices=[(1, '< 1 Year'), (2, '1 Year'), (3, '2 Years'), (4, '3 Years'), (5, '4 Years'), (6, '5 Years'), (7, '6 Years'), (8, '7 Years'), (9, '8 Years'), (10, '9 Years'), (11, '10 Years'), (12, 'More than 10 Years'), (13, 'Long as possible')], null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='planned_method_of_discharge',
            field=models.IntegerField(blank=True, choices=[(1, 'Death'), (2, 'Aged Care'), (3, 'Sale'), (4, 'Voluntary Repayment')], null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='protected_equity',
            field=models.IntegerField(blank=True, choices=[(1, '5 %'), (2, '10 %'), (3, '15 %'), (4, '20 %'), (5, '25 %'), (6, '30 %'), (7, '35 %'), (8, '40 %'), (9, '45 %'), (10, '50 %')], null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='reason_for_thirdparty_engagement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factfind',
            name='vulnerability_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
