# Generated by Django 2.1.7 on 2019-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20190626_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='topUpDrawdownAmount',
            field=models.IntegerField(default=0),
        ),
    ]
