# Generated by Django 2.2.4 on 2020-02-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20200229_2236'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondata',
            name='case-tranRef constraint',
        ),
    ]
