# Generated by Django 2.2.4 on 2019-12-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_loan_detailedtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='clientType1',
            field=models.IntegerField(blank=True, choices=[(0, 'Borrower'), (1, 'Nominated Occupant'), (3, 'Permitted Cohabitant'), (2, 'Power of Attorney')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='clientType2',
            field=models.IntegerField(blank=True, choices=[(0, 'Borrower'), (1, 'Nominated Occupant'), (3, 'Permitted Cohabitant'), (2, 'Power of Attorney')], null=True),
        ),
    ]
