# Generated by Django 2.2.4 on 2021-02-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20210113_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factfind',
            old_name='plan_for_future_giving',
            new_name='plan_for_future_living',
        ),
    ]
