# Generated by Django 2.1.7 on 2019-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_loan_topupdrawdownamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interestPayAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='interestPayPeriod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='topUpFrequency',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='loan',
            name='topUpPeriod',
            field=models.IntegerField(default=5),
        ),
    ]
