# Generated by Django 2.2.4 on 2021-02-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_auto_20210205_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='base_specificity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='street_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='street_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
