# Generated by Django 2.2.4 on 2020-02-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20200229_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Case'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiondata',
            unique_together=set(),
        ),
    ]
