# Generated by Django 2.1.7 on 2019-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_auto_20190626_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='topUpBuffer',
            field=models.BooleanField(default=True),
        ),
    ]
