# Generated by Django 2.2.4 on 2020-02-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_auto_20200229_2326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactiondata',
            unique_together={('case', 'tranRef')},
        ),
    ]
