# Generated by Django 2.1.7 on 2019-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_loan_topupbuffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='topUpBuffer',
            field=models.IntegerField(default=True),
        ),
    ]
