# Generated by Django 2.1.7 on 2019-07-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_auto_20190629_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pensionAmount',
            field=models.IntegerField(default=0),
        ),
    ]
