# Generated by Django 2.2.4 on 2021-03-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_case_donotmarket'),
        ('case', '0014_auto_20210313_0134'),
    ]

    operations = [
    ]
