# Generated by Django 2.2.4 on 2020-02-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0014_auto_20200229_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondata',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
