# Generated by Django 2.2.4 on 2020-03-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_auto_20200229_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='summarySentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='summarySentRef',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
