# Generated by Django 2.1.7 on 2019-07-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_auto_20190702_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lossdata',
            name='followUp',
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='purposeCare',
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='purposeGive',
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='purposeLive',
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='purposeRefi',
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='purposeTopUp',
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='ragStatus',
        ),
        migrations.AddField(
            model_name='lossdata',
            name='doNotMarket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='topUpBuffer',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='topUpFrequency',
            field=models.IntegerField(choices=[(1, 'fortnightly'), (2, 'monthly')], default=2),
        ),
    ]
