# Generated by Django 2.2.4 on 2020-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_auto_20200308_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='preferredName_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='preferredName_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
