# Generated by Django 2.2.4 on 2020-03-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0017_auto_20200313_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundeddata',
            old_name='application',
            new_name='approved',
        ),
    ]
