# Generated by Django 2.2.4 on 2020-03-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_auto_20200314_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='caseType',
            new_name='caseStage',
        ),
    ]
