# Generated by Django 2.2.4 on 2021-03-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_case_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='firstname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lastname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
