# Generated by Django 2.2.4 on 2021-03-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_auto_20210313_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='referrer',
            field=models.IntegerField(choices=[(-1, 'Unassigned'), (0, 'Phone'), (1, 'Email'), (3, 'Web'), (6, 'Social'), (2, 'Calculator'), (5, 'Partner'), (4, 'Broker'), (7, 'Adviser'), (100, 'Other')], default=-1),
        ),
    ]
