# Generated by Django 2.2.4 on 2020-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0020_case_apptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='refCaseUID',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
