# Generated by Django 2.2.4 on 2021-03-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0020_auto_20210317_1328'),
        ('case', '0020_auto_20210317_1608'),
    ]

    operations = [
    ]
