# Generated by Django 2.2.4 on 2021-03-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0020_case_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='firstname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='lastname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.RemoveField(
            model_name='lossdata',
            name='notProceedingReason',
        ),
        migrations.AlterField(
            model_name='lossdata',
            name='closeReason',
            field=models.IntegerField(blank=True, choices=[(1, 'Below minimum age'), (2, 'Invalid or rejected refer postcode'), (3, 'Below minimum loan amount'), (4, 'Above maximum loan amount'), (5, 'Refinance too large'), (6, 'Unsuitable purpose'), (7, 'Unsuitable property'), (8, 'Unsuitable title ownership'), (9, 'Deceased borrower'), (10, 'Not proceeding'), (12, 'Doesn’t like Reverse Mortgages'), (13, 'Fees or interest rate too high'), (11, 'Other')], null=True),
        ),
    ]
