# Generated by Django 2.2.4 on 2020-03-18 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0022_auto_20200316_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='referralUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caseReferralUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
