# Generated by Django 2.2.4 on 2021-04-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0023_auto_20210325_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseStage',
            field=models.IntegerField(choices=[(7, 'Unqualified / Lead created'), (8, 'Marketing Qualified'), (9, 'SQ - General Info'), (10, 'SQ - Brochure sent'), (11, 'SQ - Customer summary sent'), (12, 'SQ - Future call'), (13, 'Sales Active'), (0, 'Discovery'), (2, 'Converted'), (4, 'Application'), (5, 'Documentation'), (6, 'Funded'), (3, 'Closed')]),
        ),
    ]
