# Generated by Django 2.2.4 on 2021-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0023_auto_20210325_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='followUp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
