# Generated by Django 2.2.4 on 2020-03-19 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case', '0023_case_referraluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='referralUser',
        ),
        migrations.AddField(
            model_name='case',
            name='referralCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caseReferralCompany', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='referralRepNo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
