# Generated by Django 2.2.4 on 2021-03-25 01:34

from django.db import migrations
from config.celery import app
from django.contrib.contenttypes.models import ContentType
from django_comments.models import Comment
from django.utils import timezone


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Case = apps.get_model("case", "Case")
    #Comment = apps.get_model("django_comments", "Comment")

    db_alias = schema_editor.connection.alias

    cases = Case.objects.using(db_alias).all()
    for case in cases:
        note = Comment(
            content_type=ContentType.objects.get_for_model(case),
            object_pk=case.caseID,
            user_name='Unknown',
            user_email='',
            user_url='',
            comment=case.caseNotes,
            submit_date=timezone.now(),
            site_id=1,
            is_public=True,
            is_removed=False
        )
        note.save()
        app.send_task('SF_Sync_Case_Notes', kwargs={'caseUID': str(case.caseUID)})


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Comment.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_case_deleted_on'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
