# Generated by Django 2.2.4 on 2020-03-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_auto_20200320_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionData',
        ),
    ]
