# Generated by Django 2.2.4 on 2020-03-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_delete_transactiondata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundedData',
        ),
    ]
