# Generated by Django 2.2.4 on 2021-04-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0027_auto_20210409_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='email',
            new_name='email_1',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='phoneNumber',
            new_name='phoneNumber_1',
        ),
    ]
