# Generated by Django 2.2.4 on 2021-04-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0028_auto_20210409_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='case',
            name='lastname',
        ),
    ]
