# Generated by Django 2.2.4 on 2020-04-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0028_auto_20200410_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'Refinance'), (3, 'Live'), (1, 'Top Up'), (5, 'Care'), (4, 'Give')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='drawdownFrequency',
            field=models.IntegerField(blank=True, choices=[(1, 'fortnightly'), (2, 'monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'Mortgage'), (1, 'Investment'), (6, 'Transport, Travel, and Other'), (7, 'Lum Sum'), (2, 'Contingency'), (5, 'Renovations'), (3, 'Regular Draw-down'), (4, 'Give to Family')]),
        ),
    ]
