# Generated by Django 2.2.4 on 2021-04-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0029_auto_20210409_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ineligible_reason',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='case',
            name='maxDrawdownAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='maxDrawdownMonthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='maxLVR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='maxLoanAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
