# Generated by Django 2.2.4 on 2020-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0029_auto_20200410_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpurposes',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'Care'), (1, 'Top Up'), (2, 'Refinance'), (3, 'Live'), (4, 'Give')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'Lum Sum'), (6, 'Transport, Travel, and Other'), (1, 'Investment'), (8, 'Mortgage'), (3, 'Regular Draw-down'), (4, 'Give to Family'), (2, 'Contingency'), (5, 'Renovations')]),
        ),
    ]
