# Generated by Django 2.2.4 on 2020-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0030_auto_20200410_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ('-updated',), 'verbose_name_plural': 'Case'},
        ),
        migrations.AlterModelOptions(
            name='factfind',
            options={'verbose_name_plural': 'Case Fact Find'},
        ),
        migrations.AlterModelOptions(
            name='funddetail',
            options={'ordering': ('fundName',), 'verbose_name_plural': 'Superfund Definitions'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': 'Case Loan Details'},
        ),
        migrations.AlterModelOptions(
            name='loanpurposes',
            options={'verbose_name_plural': 'Case Loan Purposes'},
        ),
        migrations.AlterModelOptions(
            name='lossdata',
            options={'verbose_name_plural': 'Case Loss Data'},
        ),
        migrations.AlterModelOptions(
            name='modelsetting',
            options={'verbose_name_plural': 'Case Settings'},
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'Care'), (3, 'Live'), (2, 'Refinance'), (1, 'Top Up'), (4, 'Give')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='drawdownAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'Renovations'), (6, 'Transport, Travel, and Other'), (1, 'Investment'), (3, 'Regular Draw-down'), (7, 'Lum Sum'), (4, 'Give to Family'), (8, 'Mortgage'), (2, 'Contingency')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='planAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
