# Generated by Django 2.2.4 on 2020-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0031_auto_20200410_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'Refinance'), (1, 'Top Up'), (5, 'Care'), (4, 'Give'), (3, 'Live')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'Investment'), (3, 'Regular Draw-down'), (2, 'Contingency'), (4, 'Give to Family'), (6, 'Transport, Travel, and Other'), (5, 'Renovations'), (8, 'Mortgage'), (7, 'Lum Sum')]),
        ),
    ]
