# Generated by Django 2.2.4 on 2020-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0032_auto_20200411_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='careFrequency',
            field=models.IntegerField(choices=[(1, 'Fortnightly'), (2, 'Monthly')], default=2),
        ),
        migrations.AlterField(
            model_name='loan',
            name='topUpFrequency',
            field=models.IntegerField(choices=[(1, 'Fortnightly'), (2, 'Monthly')], default=2),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'Live'), (1, 'Top Up'), (4, 'Give'), (2, 'Refinance'), (5, 'Care')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='drawdownFrequency',
            field=models.IntegerField(choices=[(1, 'Fortnightly'), (2, 'Monthly')], default=2),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'Lum Sum'), (4, 'Give to Family'), (8, 'Mortgage'), (3, 'Regular Draw-down'), (1, 'Investment'), (6, 'Transport, Travel, and Other'), (2, 'Contingency'), (5, 'Renovations')]),
        ),
    ]
