# Generated by Django 2.2.4 on 2021-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0033_auto_20210513_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='touched_in_sf_sync',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
