# Generated by Django 2.2.4 on 2020-04-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0033_auto_20200411_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='careAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='careDescription',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='careDrawdownAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='careDrawdownDescription',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='careFrequency',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='carePeriod',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='carePlanAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='careRegularAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='giveAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='giveDescription',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='refinanceAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='renovateAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='renovateDescription',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpBuffer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpContingencyAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpContingencyDescription',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpDescription',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpDrawdownAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpFrequency',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpIncomeAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpPeriod',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='topUpPlanAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='travelAmount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='travelDescription',
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'Top Up'), (4, 'Give'), (2, 'Refinance'), (3, 'Live'), (5, 'Care')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'Lum Sum'), (2, 'Contingency'), (6, 'Transport, Travel, and Other'), (3, 'Regular Draw-down'), (8, 'Mortgage'), (1, 'Investment'), (5, 'Renovations'), (4, 'Give to Family')]),
        ),
    ]
