# Generated by Django 2.2.4 on 2021-05-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0034_case_touched_in_sf_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='channelDetail',
            field=models.IntegerField(blank=True, choices=[(11, 'Web search'), (1, 'TV Advert'), (2, 'TV Advertorial'), (3, 'Radio'), (4, 'Word of mouth'), (6, 'Competitor'), (7, 'Direct mail'), (12, 'Direct Email'), (8, 'Facebook'), (20, 'Facebook Interactive'), (21, 'Facebook Calculator'), (9, 'LinkedIn'), (10, 'Your Life Choices'), (19, 'National Seniors'), (13, 'Starts at 60'), (14, 'Care About'), (16, 'Broker Referral'), (15, 'Broker Specialist'), (17, 'Financial Adviser'), (18, 'Age Care Adviser'), (100, 'Other')], null=True),
        ),
    ]
