# Generated by Django 2.2.4 on 2021-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0034_case_touched_in_sf_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='product_type',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
