# Generated by Django 2.2.4 on 2020-04-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0034_auto_20200411_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'Care'), (4, 'Give'), (3, 'Live'), (2, 'Refinance'), (1, 'Top Up')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='drawdownFrequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Fortnightly'), (2, 'Monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'Regular Draw-down'), (7, 'Lum Sum'), (8, 'Mortgage'), (1, 'Investment'), (2, 'Contingency'), (6, 'Transport, Travel, and Other'), (4, 'Give to Family'), (5, 'Renovations')]),
        ),
    ]
