# Generated by Django 2.2.4 on 2020-04-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0035_auto_20200411_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='drawdownFrequency',
            field=models.IntegerField(blank=True, choices=[(1, 'fortnightly'), (2, 'monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'LUMP_SUM'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
