# Generated by Django 2.2.4 on 2021-05-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0035_auto_20210528_1757'),
        ('case', '0035_loan_product_type'),
    ]

    operations = [
    ]
