# Generated by Django 2.2.4 on 2020-04-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0036_auto_20200411_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='planPurposeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='purposeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='drawdownFrequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Fortnightly'), (2, 'Monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (1, 'INVESTMENT'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY')]),
        ),
    ]
