# Generated by Django 2.2.4 on 2020-04-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0037_auto_20200412_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpurposes',
            name='contractDrawdowns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (4, 'GIVE'), (3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (1, 'INVESTMENT')]),
        ),
    ]
