# Generated by Django 2.2.4 on 2021-06-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0038_auto_20210604_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='calcIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='calcLumpSum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
