# Generated by Django 2.2.4 on 2020-04-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0038_auto_20200412_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='accruedInterest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT')]),
        ),
    ]
