# Generated by Django 2.2.4 on 2020-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0039_auto_20200413_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='refFacilityUID',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='orgTotalLoanAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='orgTotalPlanAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (5, 'CARE'), (4, 'GIVE'), (2, 'REFINANCE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (6, 'TRANSPORT')]),
        ),
    ]
