# Generated by Django 2.2.4 on 2021-06-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0040_case_lead_needs_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='loan_rating',
            field=models.IntegerField(blank=True, choices=[(0, 'Simple'), (1, 'Moderate'), (2, 'Complex')], null=True),
        ),
    ]
