# Generated by Django 2.2.4 on 2020-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0040_auto_20200414_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (3, 'LIVE'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (2, 'CONTINGENCY')]),
        ),
    ]
