# Generated by Django 2.2.4 on 2021-06-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0041_case_loan_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('appType', 0), ('deleted_on__isnull', True))), fields=('phoneNumber_1', 'email_1'), name='email_phone_lead_definition_uniqueness'),
        ),
    ]
