# Generated by Django 2.2.4 on 2020-04-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0041_auto_20200415_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='investmentLabel',
            field=models.IntegerField(choices=[(0, 'Super'), (1, 'Shares / Managed Funds'), (2, 'Investment Property'), (3, 'Combined Investments')], default=0),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
