# Generated by Django 2.2.4 on 2020-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0042_auto_20200415_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='investmentLabel',
            field=models.IntegerField(choices=[(0, 'Superannuation'), (1, 'Shares / Managed Funds'), (2, 'Investment Property'), (3, 'Combined Investments')], default=0),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (4, 'GIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY')]),
        ),
    ]
