# Generated by Django 2.2.4 on 2020-04-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0042_auto_20200415_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='variationAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='investmentLabel',
            field=models.IntegerField(choices=[(0, 'Superannuation'), (1, 'Shares / Managed Funds'), (2, 'Investment Property'), (3, 'Combined Investments')], default=0),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (6, 'TRANSPORT')]),
        ),
    ]
