# Generated by Django 2.2.4 on 2020-04-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0043_auto_20200418_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (3, 'LIVE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
