# Generated by Django 2.2.4 on 2020-04-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0043_auto_20200421_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (6, 'TRANSPORT')]),
        ),
    ]
