# Generated by Django 2.2.4 on 2020-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0044_auto_20200419_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (6, 'TRANSPORT')]),
        ),
    ]
