# Generated by Django 2.2.4 on 2020-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0044_auto_20200421_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='orgTotalPlanAmount',
            new_name='orgEstablishmentFee',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='variationAmount',
            new_name='orgPurposeAmount',
        ),
        migrations.AddField(
            model_name='loan',
            name='variationFeeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='variationPurposeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='variationTotalAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (1, 'INVESTMENT')]),
        ),
    ]
