# Generated by Django 2.2.4 on 2020-04-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0045_auto_20200419_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (8, 'MORTGAGE')]),
        ),
    ]
