# Generated by Django 2.2.4 on 2021-07-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0045_case_prequaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='street',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
