# Generated by Django 2.2.4 on 2020-04-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0046_auto_20200420_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE'), (1, 'TOP_UP'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (5, 'RENOVATIONS')]),
        ),
    ]
