# Generated by Django 2.2.4 on 2020-04-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0047_auto_20200420_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (4, 'GIVE'), (3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (1, 'INVESTMENT')]),
        ),
    ]
