# Generated by Django 2.2.4 on 2021-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0048_auto_20210805_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (6, 'TRANSPORT_AND_TRAVEL'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (9, 'Regular Drawdown Funded')]),
        ),
    ]
