# Generated by Django 2.2.4 on 2020-04-27 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0045_auto_20200421_1946'),
        ('case', '0048_auto_20200423_2347'),
    ]

    operations = [
    ]
