# Generated by Django 2.2.4 on 2020-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0049_merge_20200427_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (2, 'CONTINGENCY')]),
        ),
    ]
