# Generated by Django 2.2.4 on 2021-08-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0049_auto_20210820_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (6, 'TRANSPORT_AND_TRAVEL'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (9, 'REGULAR_DRAWDOWN_FUNDED')]),
        ),
    ]
