# Generated by Django 2.2.4 on 2021-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0050_auto_20210820_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='distribution_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
