# Generated by Django 2.2.4 on 2020-04-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0050_auto_20200427_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY')]),
        ),
    ]
