# Generated by Django 2.2.4 on 2020-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0052_auto_20200427_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (4, 'GIVE'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'LUMP_SUM'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (8, 'MORTGAGE')]),
        ),
    ]
