# Generated by Django 2.2.4 on 2020-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0054_auto_20200429_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
