# Generated by Django 2.2.4 on 2020-04-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0056_auto_20200429_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS')]),
        ),
    ]
