# Generated by Django 2.2.4 on 2020-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0057_auto_20200429_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
