# Generated by Django 2.2.4 on 2020-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0058_auto_20200430_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE')]),
        ),
    ]
