# Generated by Django 2.2.4 on 2020-05-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0059_auto_20200502_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
