# Generated by Django 2.2.4 on 2020-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0060_auto_20200502_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM')]),
        ),
    ]
