# Generated by Django 2.2.4 on 2020-05-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0061_auto_20200502_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (6, 'TRANSPORT')]),
        ),
    ]
