# Generated by Django 2.2.4 on 2020-05-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0062_auto_20200503_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM')]),
        ),
    ]
