# Generated by Django 2.2.4 on 2020-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0065_auto_20200505_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'LUMP_SUM'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
