# Generated by Django 2.2.4 on 2020-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0066_auto_20200505_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
