# Generated by Django 2.2.4 on 2020-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0067_auto_20200505_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (7, 'LUMP_SUM')]),
        ),
    ]
