# Generated by Django 2.2.4 on 2020-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0068_auto_20200505_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY')]),
        ),
    ]
