# Generated by Django 2.2.4 on 2020-05-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0069_auto_20200505_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
