# Generated by Django 2.2.4 on 2020-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0071_auto_20200506_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'Refinance'), (3, 'Live'), (1, 'Top Up'), (4, 'Give'), (5, 'Care')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'Renovations'), (2, 'Contingency'), (8, 'Mortgage'), (6, 'Transport'), (4, 'Give to Family'), (7, 'Lump Sum'), (3, 'Regular Drawdown'), (1, 'Investment')]),
        ),
    ]
