# Generated by Django 2.2.4 on 2020-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0072_auto_20200506_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (5, 'CARE'), (4, 'GIVE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM')]),
        ),
    ]
