# Generated by Django 2.2.4 on 2020-05-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0074_auto_20200509_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'LUMP_SUM'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY')]),
        ),
    ]
