# Generated by Django 2.2.4 on 2020-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0075_auto_20200509_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE'), (4, 'GIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY')]),
        ),
    ]
