# Generated by Django 2.2.4 on 2020-05-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0078_auto_20200510_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (4, 'GIVE'), (3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
