# Generated by Django 2.2.4 on 2020-05-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0079_auto_20200512_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS')]),
        ),
    ]
