# Generated by Django 2.2.4 on 2020-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0080_auto_20200512_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (2, 'CONTINGENCY')]),
        ),
    ]
