# Generated by Django 2.2.4 on 2020-05-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0081_auto_20200512_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
