# Generated by Django 2.2.4 on 2020-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0082_auto_20200513_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (2, 'CONTINGENCY')]),
        ),
    ]
