# Generated by Django 2.2.4 on 2020-05-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0083_auto_20200513_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (5, 'RENOVATIONS')]),
        ),
    ]
