# Generated by Django 2.2.4 on 2020-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0084_auto_20200513_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT')]),
        ),
    ]
