# Generated by Django 2.2.4 on 2020-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0085_auto_20200515_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (1, 'INVESTMENT')]),
        ),
    ]
