# Generated by Django 2.2.4 on 2020-05-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0086_auto_20200515_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS'), (6, 'TRANSPORT')]),
        ),
    ]
