# Generated by Django 2.2.4 on 2020-05-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0087_auto_20200515_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (8, 'MORTGAGE')]),
        ),
    ]
