# Generated by Django 2.2.4 on 2020-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0088_auto_20200515_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT')]),
        ),
    ]
