# Generated by Django 2.2.4 on 2020-05-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0090_auto_20200516_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS')]),
        ),
    ]
