# Generated by Django 2.2.4 on 2020-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0092_auto_20200516_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
