# Generated by Django 2.2.4 on 2020-05-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0096_auto_20200526_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (7, 'LUMP_SUM')]),
        ),
    ]
