# Generated by Django 2.2.4 on 2020-05-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0097_auto_20200527_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
