# Generated by Django 2.2.4 on 2020-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0104_auto_20200530_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (6, 'TRANSPORT')]),
        ),
    ]
