# Generated by Django 2.2.4 on 2020-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0105_auto_20200530_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (5, 'CARE'), (3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT')]),
        ),
    ]
