# Generated by Django 2.2.4 on 2020-06-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0106_auto_20200530_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='isLowLVR',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY')]),
        ),
    ]
