# Generated by Django 2.2.4 on 2020-06-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0107_auto_20200601_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (5, 'CARE'), (3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
