# Generated by Django 2.2.4 on 2020-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0110_auto_20200601_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='applicationDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS')]),
        ),
    ]
