# Generated by Django 2.2.4 on 2020-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0111_auto_20200603_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Multi Purpose'), (1, 'Single Income'), (2, 'Single 20K')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (8, 'MORTGAGE')]),
        ),
    ]
