# Generated by Django 2.2.4 on 2020-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0112_auto_20200605_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='choiceIncome',
            new_name='choiceProduct',
        ),
        migrations.AlterField(
            model_name='case',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Multi Purpose Lump Sum'), (1, 'Single Income'), (2, 'Single 20K')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
