# Generated by Django 2.2.4 on 2020-06-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0114_auto_20200608_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY')]),
        ),
    ]
