# Generated by Django 2.2.4 on 2020-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0117_auto_20200616_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
