# Generated by Django 2.2.4 on 2020-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0118_auto_20200619_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='appUID',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN')]),
        ),
    ]
