# Generated by Django 2.2.4 on 2020-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0119_auto_20200623_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY')]),
        ),
    ]
