# Generated by Django 2.2.4 on 2020-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0120_auto_20200624_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='isReferPostcode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='referPostcodeStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY')]),
        ),
    ]
