# Generated by Django 2.2.4 on 2020-07-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0122_auto_20200629_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='maritalStatus_1',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'Defacto'), (6, 'Separated')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='maritalStatus_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'Defacto'), (6, 'Separated')], null=True),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (5, 'RENOVATIONS')]),
        ),
    ]
