# Generated by Django 2.2.4 on 2020-07-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0124_auto_20200713_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT')]),
        ),
    ]
