# Generated by Django 2.2.4 on 2020-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0125_auto_20200715_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (1, 'TOP_UP'), (4, 'GIVE'), (3, 'LIVE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (5, 'RENOVATIONS')]),
        ),
    ]
