# Generated by Django 2.2.4 on 2020-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0126_auto_20200715_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (1, 'INVESTMENT')]),
        ),
    ]
