# Generated by Django 2.2.4 on 2020-07-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0128_auto_20200717_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'TRANSPORT'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (8, 'MORTGAGE')]),
        ),
    ]
