# Generated by Django 2.2.4 on 2020-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0131_auto_20200720_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'TOP_UP'), (5, 'CARE'), (2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY')]),
        ),
    ]
