# Generated by Django 2.2.4 on 2020-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0133_auto_20200722_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE')]),
        ),
    ]
