# Generated by Django 2.2.4 on 2020-09-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0141_auto_20200902_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (6, 'TRANSPORT_AND_TRAVEL'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY')]),
        ),
    ]
