# Generated by Django 2.2.4 on 2020-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0143_auto_20200902_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='applicationDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='customerReports'),
        ),
        migrations.AlterField(
            model_name='case',
            name='maritalStatus_1',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'De Facto'), (6, 'Separated')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='maritalStatus_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'De Facto'), (6, 'Separated')], null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='responsibleDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='customerReports'),
        ),
        migrations.AlterField(
            model_name='case',
            name='summaryDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='customerReports'),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'RENOVATIONS'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT_AND_TRAVEL'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY')]),
        ),
    ]
