# Generated by Django 2.2.4 on 2020-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0145_auto_20200911_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (1, 'TOP_UP'), (3, 'LIVE'), (4, 'GIVE'), (5, 'CARE')]),
        ),
        migrations.AlterField(
            model_name='loanpurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (6, 'TRANSPORT_AND_TRAVEL'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS')]),
        ),
    ]
