# Generated by Django 2.2.4 on 2021-01-29 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('settings', '0001_initial'), ('settings', '0002_auto_20201223_1756'), ('settings', '0003_auto_20201224_0027'), ('settings', '0004_auto_20201228_1707'), ('settings', '0005_auto_20210111_0131'), ('settings', '0006_auto_20210111_0136'), ('settings', '0007_auto_20210128_2344'), ('settings', '0008_auto_20210129_0011')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoassignees_calculators', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(('is_active', True), ('profile__isCreditRep', True), ('profile__calendlyUrl__isnull', False), models.Q(_negated=True, profile__calendlyUrl=''))), related_name='autoassignees_calculators', to=settings.AUTH_USER_MODEL)),
                ('autoassignees_CARE_ABOUT', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_CARE_ABOUT', to=settings.AUTH_USER_MODEL)),
                ('autoassignees_FACEBOOK', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_FACEBOOK', to=settings.AUTH_USER_MODEL)),
                ('autoassignees_LINKEDIN', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_LINKEDIN', to=settings.AUTH_USER_MODEL)),
                ('autoassignees_NATIONAL_SENIORS', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_NATIONAL_SENIORS', to=settings.AUTH_USER_MODEL)),
                ('autoassignees_STARTS_AT_60', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_STARTS_AT_60', to=settings.AUTH_USER_MODEL)),
                ('autoassignees_YOUR_LIFE_CHOICES', models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_YOUR_LIFE_CHOICES', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
