# Generated by Django 2.2.4 on 2021-01-29 01:04

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    GlobalSettings = apps.get_model("settings", "GlobalSettings")
    GlobalSettings.objects.get_or_create(pk=1)


def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    GlobalSettings = apps.get_model("settings", "GlobalSettings")
    GlobalSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_squashed_0008_auto_20210129_0011'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]


