# Generated by Django 2.2.4 on 2020-12-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='auto_calc_users',
            new_name='autoassignees_calculators',
        ),
    ]
