# Generated by Django 2.2.4 on 2020-12-23 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201223_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_calculators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'isCreditRep': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
