# Generated by Django 2.2.4 on 2020-12-28 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20201224_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_calculators',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(('profile__isCreditRep', True), ('profile__calendlyUrl__isnull', False), models.Q(_negated=True, profile__calendlyUrl=''))), to=settings.AUTH_USER_MODEL),
        ),
    ]
