# Generated by Django 2.2.4 on 2021-06-24 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_auto_20210528_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_pre_qual',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(('is_active', True), ('profile__isCreditRep', True), ('profile__calendlyUrl__isnull', False), models.Q(_negated=True, profile__calendlyUrl=''))), related_name='autoassignees_pre_qual', to=settings.AUTH_USER_MODEL),
        ),
    ]
