# Generated by Django 2.2.4 on 2021-07-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_globalsettings_autoassignees_pre_qual'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_CARE_ABOUT_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_FACEBOOK_CALCULATOR_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_FACEBOOK_INTERACTIVE_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_FACEBOOK_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_LINKEDIN_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_NATIONAL_SENIORS_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_STARTS_AT_60_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_YOUR_LIFE_CHOICES_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_calculators_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_pre_qual_index',
            field=models.IntegerField(default=0),
        ),
    ]
