# Generated by Django 2.2.4 on 2021-07-14 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0006_auto_20210707_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_GOOGLE_MOBILE',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_GOOGLE_MOBILE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_GOOGLE_MOBILE_index',
            field=models.IntegerField(default=0),
        ),
    ]
