# Generated by Django 2.2.4 on 2021-09-06 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0007_auto_20210714_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_FACEBOOK_VISA',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_FACEBOOK_VISA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='autoassignees_FACEBOOK_VISA_index',
            field=models.IntegerField(default=0),
        ),
    ]
