# Generated by Django 2.2.4 on 2021-01-28 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20210128_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_CARE_ABOUT',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_CARE_ABOUT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_FACEBOOK',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_FACEBOOK', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_LINKEDIN',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_LINKEDIN', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_NATIONAL_SENIORS',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_NATIONAL_SENIORS', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_STARTS_AT_60',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_STARTS_AT_60', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='autoassignees_YOUR_LIFE_CHOICES',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(models.Q(is_active=True)), related_name='autoassignees_YOUR_LIFE_CHOICES', to=settings.AUTH_USER_MODEL),
        ),
    ]
