# Generated by Django 2.2.4 on 2020-03-20 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('originalCaseUID', models.UUIDField(blank=True, null=True)),
                ('sFLoanName', models.CharField(max_length=30)),
                ('sFLoanID', models.CharField(max_length=20)),
                ('sFAccountID', models.CharField(max_length=20)),
                ('sFReferrerAccount', models.CharField(blank=True, max_length=20, null=True)),
                ('amalID', models.CharField(max_length=20)),
                ('sFOriginatorID', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[('Inactive', 0), ('Active', 1), ('Repaid', 2), ('Suspended', 3)])),
                ('settlementDate', models.DateTimeField(blank=True, null=True)),
                ('lastDrawdownDate', models.DateTimeField(blank=True, null=True)),
                ('maturityDate', models.DateTimeField(blank=True, null=True)),
                ('totalLoanAmount', models.IntegerField(default=0)),
                ('totalEstablishmentFee', models.IntegerField(default=0)),
                ('totalPlanAmount', models.IntegerField(default=0)),
                ('totalPlanEstablishmentFee', models.IntegerField(default=0)),
                ('establishmentFeeRate', models.FloatField(default=0)),
                ('advancedAmount', models.IntegerField(default=0)),
                ('currentBalance', models.IntegerField(default=0)),
                ('originalLVR', models.FloatField(default=0)),
                ('currentLVR', models.FloatField(default=0)),
                ('bPayBillerCode', models.CharField(blank=True, max_length=20, null=True)),
                ('bPAYReference', models.CharField(blank=True, max_length=20, null=True)),
                ('relationshipNotes', models.TextField(blank=True, null=True)),
                ('bsbNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('bankAccountNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('lastAnnualService', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
