# Generated by Django 2.2.4 on 2020-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(4, 'Give'), (5, 'Care'), (1, 'Top Up'), (2, 'Refinance'), (3, 'Live')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(2, 'Contingency'), (7, 'Lump Sum'), (5, 'Renovations'), (4, 'Give to Family'), (6, 'Transport and Travel'), (8, 'Mortgage'), (1, 'Investment'), (3, 'Regular Drawdown')]),
        ),
    ]
