# Generated by Django 2.2.4 on 2020-03-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='bPAYReference',
            new_name='bPayReference',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='lastDrawdownDate',
            new_name='maxDrawdownDate',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='sFAccountID',
            new_name='sfAccountID',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='sFLoanID',
            new_name='sfLoanID',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='sFLoanName',
            new_name='sfLoanName',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='sFReferrerAccount',
            new_name='sfReferrerAccount',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='originalLVR',
        ),
    ]
