# Generated by Django 2.2.4 on 2020-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_auto_20200926_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'Care'), (3, 'Live'), (4, 'Give'), (2, 'Refinance'), (1, 'Top Up')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'Regular Drawdown'), (6, 'Transport and Travel'), (8, 'Mortgage'), (7, 'Lump Sum'), (2, 'Contingency'), (5, 'Renovations'), (4, 'Give to Family'), (1, 'Investment')]),
        ),
    ]
