# Generated by Django 2.2.4 on 2020-03-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_auto_20200320_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='sfLoanName',
            field=models.CharField(max_length=60),
        ),
    ]
