# Generated by Django 2.2.4 on 2020-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0003_auto_20201016_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'Refinance'), (5, 'Care'), (4, 'Give'), (1, 'Top Up'), (3, 'Live')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(8, 'Mortgage'), (1, 'Investment'), (7, 'Lump Sum'), (6, 'Transport and Travel'), (5, 'Renovations'), (3, 'Regular Drawdown'), (2, 'Contingency'), (4, 'Give to Family')]),
        ),
    ]
