# Generated by Django 2.2.4 on 2020-03-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0003_auto_20200320_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='sfLoanID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Repaid'), (3, 'Suspended')]),
        ),
    ]
