# Generated by Django 2.2.4 on 2020-10-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0004_auto_20201016_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'Refinance'), (3, 'Live'), (5, 'Care'), (1, 'Top Up'), (4, 'Give')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'Give to Family'), (6, 'Transport and Travel'), (3, 'Regular Drawdown'), (5, 'Renovations'), (7, 'Lump Sum'), (8, 'Mortgage'), (2, 'Contingency'), (1, 'Investment')]),
        ),
    ]
