# Generated by Django 2.2.4 on 2020-03-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0004_auto_20200321_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='sfLoanName',
            field=models.CharField(max_length=80),
        ),
    ]
