# Generated by Django 2.2.4 on 2020-10-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0005_auto_20201016_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'Top Up'), (3, 'Live'), (4, 'Give'), (5, 'Care'), (2, 'Refinance')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(4, 'Give to Family'), (2, 'Contingency'), (6, 'Transport and Travel'), (5, 'Renovations'), (8, 'Mortgage'), (3, 'Regular Drawdown'), (7, 'Lump Sum'), (1, 'Investment')]),
        ),
    ]
