# Generated by Django 2.2.4 on 2020-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0005_auto_20200321_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='amalReconciliation',
            field=models.BooleanField(default=False),
        ),
    ]
