# Generated by Django 2.2.4 on 2020-12-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0006_auto_20201022_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'Top Up'), (2, 'Refinance'), (3, 'Live'), (4, 'Give'), (5, 'Care')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'Investment'), (2, 'Contingency'), (3, 'Regular Drawdown'), (4, 'Give to Family'), (5, 'Renovations'), (6, 'Transport and Travel'), (7, 'Lump Sum'), (8, 'Mortgage')]),
        ),
    ]
