# Generated by Django 2.2.4 on 2020-03-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0006_facility_amalreconciliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='sfLoanID',
            new_name='sfID',
        ),
    ]
