# Generated by Django 2.2.4 on 2020-03-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0007_auto_20200321_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='sfLoanID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
