# Generated by Django 2.2.4 on 2020-12-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0007_auto_20201222_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='firstName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facilityroles',
            name='lastName',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='facilityroles',
            name='middleName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='facilityroles',
            name='preferredName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
