# Generated by Django 2.2.4 on 2020-03-21 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0008_facility_sfloanid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('transactionDate', models.DateTimeField(blank=True, null=True)),
                ('effectiveDate', models.DateTimeField(blank=True, null=True)),
                ('tranRef', models.CharField(max_length=30)),
                ('debitAmount', models.FloatField(blank=True, default=0, null=True)),
                ('creditAmount', models.FloatField(blank=True, default=0, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
            ],
            options={
                'verbose_name_plural': 'Transaction Data',
                'unique_together': {('facility', 'tranRef')},
            },
        ),
    ]
