# Generated by Django 2.2.4 on 2021-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0008_auto_20201229_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityroles',
            name='sfRoleID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
