# Generated by Django 2.2.4 on 2020-03-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0009_transactiondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterField(
            model_name='facility',
            name='originalCaseUID',
            field=models.UUIDField(unique=True),
        ),
    ]
