# Generated by Django 2.2.4 on 2021-03-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0009_facilityroles_sfroleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='sfContactID',
            field=models.CharField(max_length=20),
        ),
    ]
