# Generated by Django 2.2.4 on 2020-03-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0010_auto_20200321_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='meetingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
