# Generated by Django 2.2.4 on 2020-03-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0011_facility_meetingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='approvedAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='dischargeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='totalValuation',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
