# Generated by Django 2.2.4 on 2021-06-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0012_auto_20210520_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='product_type',
            field=models.CharField(blank=True, choices=[('HHC.RM.2018', 'HHC.RM.2018'), ('HHC.RM.2021', 'HHC.RM.2021')], max_length=11, null=True),
        ),
    ]
