# Generated by Django 2.2.4 on 2020-03-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0012_auto_20200322_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='advancedAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='approvedAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='currentBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='totalEstablishmentFee',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='totalLoanAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='totalPlanAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facility',
            name='totalPlanEstablishmentFee',
            field=models.FloatField(default=0),
        ),
    ]
