# Generated by Django 2.2.4 on 2021-06-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0013_facility_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='sfLoanName',
            field=models.CharField(max_length=100),
        ),
    ]
