# Generated by Django 2.2.4 on 2020-03-22 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0013_auto_20200322_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='sFOriginatorID',
            new_name='sfOriginatorID',
        ),
    ]
