# Generated by Django 2.2.4 on 2021-08-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0014_auto_20210622_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'Investment'), (2, 'Contingency'), (3, 'Regular Drawdown'), (4, 'Give to Family'), (5, 'Renovations'), (6, 'Transport and Travel'), (7, 'Lump Sum'), (8, 'Mortgage'), (9, 'Regular Drawdown Funded')]),
        ),
    ]
