# Generated by Django 2.2.4 on 2020-03-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0014_auto_20200322_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sFContactID', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'Principal Borrower'), (1, 'Secondary Borrower'), (2, 'Borrower'), (3, 'Nominated Occupant'), (4, 'Permitted Cohabitant'), (5, 'Power of Attorney'), (6, 'Authorised 3rd Party'), (7, 'Distribution Partner Contact'), (8, 'Adviser'), (9, 'Loan Originator'), (10, 'Loan Writer'), (11, 'Loan Originator'), (12, 'Valuer'), (13, 'Executor')])),
                ('isPrimaryContact', models.BooleanField(default=False)),
                ('contactAuthorisation', models.IntegerField(choices=[(0, 'None'), (1, 'Full'), (2, 'Information Only')])),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('firstName', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredName', models.CharField(blank=True, max_length=30, null=True)),
                ('salutation', models.IntegerField(choices=[(1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.'), (4, 'Dr.'), (5, 'Prof.')])),
                ('gender', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')])),
                ('maritalStatus', models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'Defacto')])),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=40, null=True)),
                ('suburb', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.IntegerField(choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')])),
                ('postcode', models.CharField(max_length=4)),
                ('roleNotes', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
            ],
        ),
    ]
