# Generated by Django 2.2.4 on 2020-03-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0015_facilityroles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityroles',
            old_name='sFContactID',
            new_name='sfContactID',
        ),
    ]
