# Generated by Django 2.2.4 on 2020-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0017_auto_20200324_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='sfContactID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
