# Generated by Django 2.2.4 on 2020-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0018_auto_20200325_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='street',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='facilityroles',
            name='suburb',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
