# Generated by Django 2.2.4 on 2020-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0019_auto_20200325_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
