# Generated by Django 2.2.4 on 2020-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0020_auto_20200325_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='contactAuthorisation',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Full'), (2, 'Information Only')], null=True),
        ),
    ]
