# Generated by Django 2.2.4 on 2020-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0021_auto_20200325_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='facilityroles',
            name='maritalStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Single'), (2, 'Married'), (3, 'Divorced'), (4, 'Widowed'), (5, 'Defacto')], null=True),
        ),
        migrations.AlterField(
            model_name='facilityroles',
            name='salutation',
            field=models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.'), (4, 'Dr.'), (5, 'Prof.')], null=True),
        ),
    ]
