# Generated by Django 2.2.4 on 2020-03-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0022_auto_20200325_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')], null=True),
        ),
    ]
