# Generated by Django 2.2.4 on 2020-03-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0023_auto_20200325_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='postcode',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
