# Generated by Django 2.2.4 on 2020-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0024_auto_20200325_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityroles',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
