# Generated by Django 2.2.4 on 2020-03-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0025_facilityroles_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityroles',
            name='contactAuthorisation',
        ),
        migrations.AddField(
            model_name='facilityroles',
            name='isAuthorised',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Refer POA')], null=True),
        ),
        migrations.AddField(
            model_name='facilityroles',
            name='isInformation',
            field=models.BooleanField(default=False),
        ),
    ]
