# Generated by Django 2.2.4 on 2020-03-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0027_auto_20200328_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='isAuthorised',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Refer POA')], default=0),
        ),
    ]
