# Generated by Django 2.2.4 on 2020-03-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0028_auto_20200328_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfPropertyID', models.CharField(max_length=20, unique=True)),
                ('street', models.CharField(blank=True, max_length=60, null=True)),
                ('suburb', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.IntegerField(blank=True, choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')], null=True)),
                ('postcode', models.CharField(blank=True, max_length=4, null=True)),
                ('propertyType', models.CharField(blank=True, max_length=60, null=True)),
                ('insuranceCompany', models.CharField(blank=True, max_length=60, null=True)),
                ('insurancePolicy', models.CharField(blank=True, max_length=60, null=True)),
                ('insuranceExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('insuredAmount', models.FloatField(blank=True, default=0, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Property',
            },
        ),
        migrations.AlterModelOptions(
            name='facilityroles',
            options={'verbose_name_plural': 'Facility Roles'},
        ),
        migrations.CreateModel(
            name='FacilityPropertyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuationAmount', models.FloatField(blank=True, default=0, null=True)),
                ('valuationDate', models.DateTimeField(blank=True, null=True)),
                ('valuationType', models.IntegerField(choices=[(0, 'Auto Valuation'), (1, 'Full Valuation'), (2, 'Rates Valuation')], default=0)),
                ('valuationCompany', models.CharField(blank=True, max_length=20, null=True)),
                ('valuerName', models.CharField(blank=True, max_length=40, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.FacilityProperty')),
            ],
        ),
    ]
