# Generated by Django 2.2.4 on 2020-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0029_auto_20200328_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitypropertyval',
            options={'verbose_name_plural': 'Facility Property Valuation'},
        ),
        migrations.AlterField(
            model_name='facilityproperty',
            name='insuranceCompany',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='facilityproperty',
            name='street',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
