# Generated by Django 2.2.4 on 2020-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0030_auto_20200328_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityproperty',
            name='insuranceCompany',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='facilityproperty',
            name='insurancePolicy',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
