# Generated by Django 2.2.4 on 2020-03-28 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0031_auto_20200328_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityPurposes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfPurposeID', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('intention', models.CharField(max_length=20)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('drawdownAmount', models.FloatField(blank=True, default=0, null=True)),
                ('drawdownFrequency', models.IntegerField(default=0)),
                ('drawdownStartDate', models.DateTimeField(blank=True, null=True)),
                ('planAmount', models.FloatField(blank=True, default=0, null=True)),
                ('planPeriod', models.IntegerField(default=0)),
                ('topUpBuffer', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
            ],
        ),
    ]
