# Generated by Django 2.2.4 on 2020-03-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0032_facilitypurposes'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitypurposes',
            name='drawdownEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
