# Generated by Django 2.2.4 on 2020-03-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0033_facilitypurposes_drawdownenddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitypurposes',
            options={'verbose_name_plural': 'Facility Purposes'},
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='drawdownFrequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
