# Generated by Django 2.2.4 on 2020-03-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0034_auto_20200329_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='planPeriod',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
