# Generated by Django 2.2.4 on 2020-03-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0035_auto_20200329_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.CharField(max_length=30),
        ),
    ]
