# Generated by Django 2.2.4 on 2020-03-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0036_auto_20200329_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='totalPlanPurposeAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='totalPurposeAmount',
            field=models.FloatField(default=0),
        ),
    ]
