# Generated by Django 2.2.4 on 2020-03-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0037_auto_20200329_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateTimeField()),
                ('eventType', models.IntegerField(choices=[(1, 'Loan Settlement'), (2, 'Loan Variation'), (3, 'Loan Repaid'), (4, 'Death of a Borrower'), (5, 'Repayment Event')])),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Events',
            },
        ),
    ]
