# Generated by Django 2.2.4 on 2020-03-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0038_facilityevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionData',
            new_name='FacilityTransactions',
        ),
    ]
