# Generated by Django 2.2.4 on 2020-03-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0039_auto_20200329_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitytransactions',
            options={'verbose_name_plural': 'Facility Transactions'},
        ),
        migrations.AddField(
            model_name='facilityevents',
            name='eventNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
