# Generated by Django 2.2.4 on 2020-03-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0040_auto_20200329_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='amalBreach',
            field=models.BooleanField(default=False),
        ),
    ]
