# Generated by Django 2.2.4 on 2020-04-04 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicing', '0041_facility_amalbreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherEnquirerName', models.CharField(blank=True, max_length=60, null=True)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('contactPhone', models.CharField(blank=True, max_length=15, null=True)),
                ('enquiryNotes', models.TextField(blank=True, null=True)),
                ('actionNotes', models.TextField(blank=True, null=True)),
                ('actioned', models.BooleanField(default=False)),
                ('actionDate', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actionedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actionedBy', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
                ('identifiedEnquirer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicing.FacilityRoles')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
