# Generated by Django 2.2.4 on 2020-04-06 13:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0042_facilityenquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityenquiry',
            options={'verbose_name_plural': 'Facility Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='facilityroles',
            options={'ordering': ('role',), 'verbose_name_plural': 'Facility Roles'},
        ),
        migrations.AlterField(
            model_name='facilityenquiry',
            name='actioned',
            field=models.BooleanField(choices=[(False, 'Open'), (True, 'Actioned')], default=False),
        ),
        migrations.CreateModel(
            name='FacilityAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('amountRequested', models.FloatField(blank=True, default=0, null=True)),
                ('amountEstablishmentFee', models.FloatField(blank=True, default=0, null=True)),
                ('amountTotal', models.FloatField(blank=True, default=0, null=True)),
                ('establishmentFeeRate', models.FloatField(blank=True, default=0, null=True)),
                ('requestedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('requestedRole', models.CharField(blank=True, max_length=60, null=True)),
                ('requestedEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('requestedIP', models.CharField(blank=True, max_length=45, null=True)),
                ('requestedDate', models.DateTimeField(blank=True, null=True)),
                ('choicePurposes', models.BooleanField(default=False)),
                ('choiceNoMaterialChange', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
            ],
            options={
                'verbose_name_plural': 'Facility Additional Drawdown',
            },
        ),
    ]
