# Generated by Django 2.2.4 on 2020-04-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0043_auto_20200406_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityadditional',
            name='requestedBy',
        ),
        migrations.AddField(
            model_name='facilityadditional',
            name='requestedFirstName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='facilityadditional',
            name='requestedLastName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
