# Generated by Django 2.2.4 on 2020-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0044_auto_20200407_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityadditional',
            name='amountRequested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
