# Generated by Django 2.2.4 on 2020-04-08 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0045_auto_20200407_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityadditional',
            name='requestedFirstName',
        ),
        migrations.RemoveField(
            model_name='facilityadditional',
            name='requestedLastName',
        ),
        migrations.RemoveField(
            model_name='facilityadditional',
            name='requestedRole',
        ),
        migrations.RemoveField(
            model_name='facilityenquiry',
            name='enquiryNotes',
        ),
        migrations.AddField(
            model_name='facilityadditional',
            name='identifiedRequester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicing.FacilityRoles'),
        ),
    ]
