# Generated by Django 2.2.4 on 2020-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0046_auto_20200408_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityroles',
            name='middleName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
