# Generated by Django 2.2.4 on 2020-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0047_facilityroles_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityproperty',
            name='propertyType',
        ),
        migrations.AddField(
            model_name='facilityproperty',
            name='dwellingType',
            field=models.IntegerField(blank=True, choices=[(0, 'House'), (1, 'Apartment')], null=True),
        ),
    ]
