# Generated by Django 2.2.4 on 2020-07-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0049_auto_20200508_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='lastAnnualService',
            new_name='nextAnnualService',
        ),
    ]
