# Generated by Django 2.2.4 on 2020-07-15 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0050_auto_20200706_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAnnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('respondentEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('responseIP', models.CharField(blank=True, max_length=45, null=True)),
                ('responseDate', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicing.Facility')),
                ('identifiedRespondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicing.FacilityRoles')),
            ],
            options={
                'verbose_name_plural': 'Facility Annual Review',
            },
        ),
    ]
