# Generated by Django 2.2.4 on 2020-07-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0051_facilityannual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityadditional',
            old_name='requestedEmail',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='facilityadditional',
            old_name='identifiedRequester',
            new_name='identifiedContact',
        ),
        migrations.RenameField(
            model_name='facilityannual',
            old_name='respondentEmail',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='facilityannual',
            old_name='identifiedRespondent',
            new_name='identifiedContact',
        ),
    ]
