# Generated by Django 2.2.4 on 2020-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0052_auto_20200715_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityannual',
            name='choiceHouseholdCPersons',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='choiceHouseholdConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='householdNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
