# Generated by Django 2.2.4 on 2020-07-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0053_auto_20200717_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityannual',
            old_name='choiceHouseholdCPersons',
            new_name='choiceHouseholdPersons',
        ),
    ]
