# Generated by Django 2.2.4 on 2020-07-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0054_auto_20200717_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityannual',
            name='choiceInsuranceConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='choiceRatesConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='choiceRepairsConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='homeNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
