# Generated by Django 2.2.4 on 2020-07-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0055_auto_20200719_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityannual',
            name='choiceCallbackConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='choiceRegularConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='choiceUndrawnConfirm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='needNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
