# Generated by Django 2.2.4 on 2020-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0057_auto_20200720_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityannual',
            name='reviewDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
