# Generated by Django 2.2.4 on 2020-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0058_facilityannual_reviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='nextAnnualService',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilityannual',
            name='reviewDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
