# Generated by Django 2.2.4 on 2020-07-22 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0059_auto_20200722_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityannual',
            name='reviewDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
