# Generated by Django 2.2.4 on 2020-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0060_auto_20200722_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityannual',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facilityannual',
            name='reviewNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
