# Generated by Django 2.2.4 on 2020-08-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0061_auto_20200723_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='annualServiceNotification',
            field=models.BooleanField(default=False),
        ),
    ]
