# Generated by Django 2.2.4 on 2020-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0062_facility_annualservicenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityroles',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
