# Generated by Django 2.2.4 on 2020-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0063_auto_20200819_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'REFINANCE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(1, 'INVESTMENT'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (6, 'TRANSPORT_AND_TRAVEL')]),
        ),
    ]
