# Generated by Django 2.2.4 on 2020-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0066_auto_20200902_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'Top Up'), (3, 'Live'), (4, 'Give'), (5, 'Care'), (2, 'Refinance')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'Transport and Travel'), (8, 'Mortgage'), (7, 'Lump Sum'), (1, 'Investment'), (2, 'Contingency'), (4, 'Give to Family'), (5, 'Renovations'), (3, 'Regular Drawdown')]),
        ),
    ]
