# Generated by Django 2.2.4 on 2020-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0067_auto_20200911_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(2, 'Refinance'), (1, 'Top Up'), (3, 'Live'), (5, 'Care'), (4, 'Give')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(6, 'Transport and Travel'), (4, 'Give to Family'), (2, 'Contingency'), (8, 'Mortgage'), (3, 'Regular Drawdown'), (7, 'Lump Sum'), (5, 'Renovations'), (1, 'Investment')]),
        ),
    ]
