# Generated by Django 2.2.4 on 2020-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0068_auto_20200911_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitypurposes',
            name='category',
            field=models.IntegerField(choices=[(1, 'Top Up'), (4, 'Give'), (2, 'Refinance'), (3, 'Live'), (5, 'Care')]),
        ),
        migrations.AlterField(
            model_name='facilitypurposes',
            name='intention',
            field=models.IntegerField(choices=[(5, 'Renovations'), (6, 'Transport and Travel'), (2, 'Contingency'), (3, 'Regular Drawdown'), (8, 'Mortgage'), (1, 'Investment'), (7, 'Lump Sum'), (4, 'Give to Family')]),
        ),
    ]
