# Generated by Django 2.2.4 on 2020-04-18 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200402_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calcUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('loanType', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('age_1', models.IntegerField()),
                ('age_2', models.IntegerField(blank=True, null=True)),
                ('dwellingType', models.BooleanField(default=True)),
                ('valuation', models.IntegerField()),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('maxLoanAmount', models.IntegerField(blank=True, null=True)),
                ('maxLVR', models.FloatField(blank=True, null=True)),
                ('errorText', models.CharField(blank=True, max_length=40, null=True)),
                ('isTopUp', models.BooleanField(blank=True, null=True)),
                ('isRefi', models.BooleanField(blank=True, null=True)),
                ('isLive', models.BooleanField(blank=True, null=True)),
                ('isGive', models.BooleanField(blank=True, null=True)),
                ('isCare', models.BooleanField(blank=True, null=True)),
                ('calcTopUp', models.IntegerField(blank=True, null=True)),
                ('calcRefi', models.IntegerField(blank=True, null=True)),
                ('calcLive', models.IntegerField(blank=True, null=True)),
                ('calcGive', models.IntegerField(blank=True, null=True)),
                ('calcCare', models.IntegerField(blank=True, null=True)),
                ('calcTotal', models.IntegerField(blank=True, null=True)),
                ('payIntAmount', models.IntegerField(blank=True, null=True)),
                ('payIntPeriod', models.IntegerField(blank=True, null=True)),
                ('numberFirst', models.IntegerField(blank=True, null=True)),
                ('numberLast', models.IntegerField(blank=True, null=True)),
                ('flatNumberPrefix', models.CharField(blank=True, max_length=30, null=True)),
                ('flatNumber', models.IntegerField(blank=True, null=True)),
                ('flatNumberSuffix', models.CharField(blank=True, max_length=30, null=True)),
                ('levelNumber', models.IntegerField(blank=True, null=True)),
                ('streetName', models.CharField(blank=True, max_length=30, null=True)),
                ('streetType', models.CharField(blank=True, max_length=30, null=True)),
                ('suburb', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('retrieved', models.IntegerField(blank=True, default=0, null=True)),
                ('retrievedDate', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
