# Generated by Django 2.2.4 on 2020-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200926_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (7, 'LUMP_SUM'), (6, 'TRANSPORT_AND_TRAVEL'), (5, 'RENOVATIONS'), (1, 'INVESTMENT')], null=True),
        ),
    ]
