# Generated by Django 2.2.4 on 2020-10-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201016_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(6, 'TRANSPORT_AND_TRAVEL'), (4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
