# Generated by Django 2.2.4 on 2020-04-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_incomecalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecalculator',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
