# Generated by Django 2.2.4 on 2020-04-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_incomecalculator_streetaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecalculator',
            name='flatNumber',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='flatNumberPrefix',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='flatNumberSuffix',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='levelNumber',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='numberFirst',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='numberLast',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='streetName',
        ),
        migrations.RemoveField(
            model_name='incomecalculator',
            name='streetType',
        ),
        migrations.AlterField(
            model_name='incomecalculator',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incomecalculator',
            name='suburb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
