# Generated by Django 2.2.4 on 2020-10-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201016_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (1, 'TOP_UP'), (4, 'GIVE'), (5, 'CARE'), (3, 'LIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT_AND_TRAVEL'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
