# Generated by Django 2.2.4 on 2020-04-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200419_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecalculator',
            name='choiceMortgage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomecalculator',
            name='choiceOtherNeeds',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
