# Generated by Django 2.2.4 on 2020-04-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200420_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecalculator',
            name='maxDrawdownAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
