# Generated by Django 2.2.4 on 2020-04-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_incomecalculator_maxdrawdownamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecalculator',
            name='maxDrawdownMonthly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
