# Generated by Django 2.2.4 on 2020-04-27 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_incomecalculator_maxdrawdownmonthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('loanType', models.BooleanField(default=True)),
                ('age_1', models.IntegerField()),
                ('age_2', models.IntegerField(blank=True, null=True)),
                ('dwellingType', models.BooleanField(default=True)),
                ('valuation', models.IntegerField()),
                ('surname_1', models.CharField(blank=True, max_length=30, null=True)),
                ('firstname_1', models.CharField(blank=True, max_length=30, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=80, null=True)),
                ('suburb', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('maxLoanAmount', models.IntegerField(blank=True, null=True)),
                ('maxDrawdownAmount', models.IntegerField(blank=True, null=True)),
                ('maxDrawdownMonthly', models.IntegerField(blank=True, null=True)),
                ('maxLVR', models.FloatField(blank=True, null=True)),
                ('choiceOtherNeeds', models.BooleanField(blank=True, null=True)),
                ('choiceMortgage', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IncomeCalculator',
        ),
        migrations.DeleteModel(
            name='LowLVR',
        ),
    ]
