# Generated by Django 2.2.4 on 2020-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200427_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='phoneNumber',
            new_name='mobileNumber',
        ),
        migrations.AddField(
            model_name='application',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pinExpiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
