# Generated by Django 2.2.4 on 2020-04-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200429_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='mobileNumber',
            new_name='mobile',
        ),
    ]
