# Generated by Django 2.2.4 on 2020-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200429_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='age_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dwellingType',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='valuation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
