# Generated by Django 2.2.4 on 2020-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20200430_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='choiceIncome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='choiceOwnership',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
