# Generated by Django 2.2.4 on 2020-05-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20200502_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='choiceMortgage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='choiceOtherNeeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='choiceOwnership',
            field=models.BooleanField(default=True),
        ),
    ]
