# Generated by Django 2.2.4 on 2020-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20200502_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='appStatus',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In-Progress'), (2, 'Expired'), (3, 'Submitted'), (4, 'Contact')], default=0),
        ),
    ]
