# Generated by Django 2.2.4 on 2020-05-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_application_appstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthdate_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sex_1',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
    ]
