# Generated by Django 2.2.4 on 2020-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20200505_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dwellingType',
            field=models.BooleanField(choices=[(0, 'House'), (1, 'Apartment')], default=True),
        ),
    ]
