# Generated by Django 2.2.4 on 2020-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_auto_20200505_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birthdate_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='firstname_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sex_2',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='surname_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
