# Generated by Django 2.2.4 on 2020-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20200505_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dwellingType',
            field=models.IntegerField(choices=[(0, 'House'), (1, 'Apartment')], default=True),
        ),
    ]
