# Generated by Django 2.2.4 on 2020-05-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_auto_20200505_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='choiceMortgage',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='choiceOtherNeeds',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='choiceOwnership',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
