# Generated by Django 2.2.4 on 2020-05-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20200505_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='productType',
            field=models.IntegerField(choices=[(0, 'Lump Sum'), (1, 'Income')], default=0),
        ),
    ]
