# Generated by Django 2.2.4 on 2020-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_application_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='drawdownAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='drawdownFrequency',
            field=models.IntegerField(blank=True, choices=[(1, 'Fortnightly'), (2, 'Monthly')], null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='drawdownPeriod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
