# Generated by Django 2.2.4 on 2020-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20200506_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='drawdownFrequency',
            field=models.IntegerField(choices=[(1, 'Fortnightly'), (2, 'Monthly')], default=2),
        ),
    ]
