# Generated by Django 2.2.4 on 2020-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_auto_20200508_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contractDrawdowns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='planAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='planDrawdowns',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
