# Generated by Django 2.2.4 on 2020-05-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20200509_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='drawdownPeriod',
            new_name='planPeriod',
        ),
    ]
