# Generated by Django 2.2.4 on 2020-05-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20200509_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='contractDrawdowns',
        ),
        migrations.RemoveField(
            model_name='application',
            name='drawdownAmount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='drawdownFrequency',
        ),
        migrations.RemoveField(
            model_name='application',
            name='planAmount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='planDrawdowns',
        ),
        migrations.RemoveField(
            model_name='application',
            name='planPeriod',
        ),
        migrations.AddField(
            model_name='application',
            name='establishmentFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='planEstablishmentFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='planPurposeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='purposeAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='totalLoanAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='totalPlanAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ApplicationPurposes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE'), (4, 'GIVE'), (1, 'TOP_UP')])),
                ('intention', models.IntegerField(choices=[(1, 'INVESTMENT'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY')])),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('drawdownAmount', models.IntegerField(blank=True, default=0, null=True)),
                ('drawdownFrequency', models.IntegerField(choices=[(1, 'Fortnightly'), (2, 'Monthly')], default=2)),
                ('contractDrawdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('planDrawdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('planAmount', models.IntegerField(blank=True, default=0, null=True)),
                ('planPeriod', models.IntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'verbose_name_plural': 'Application Loan Purposes',
            },
        ),
    ]
