# Generated by Django 2.2.4 on 2020-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20200510_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='actualLVR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(choices=[(5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE')]),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(choices=[(3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (6, 'TRANSPORT')]),
        ),
    ]
