# Generated by Django 2.2.4 on 2020-05-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_auto_20200510_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='summaryDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (4, 'GIVE'), (3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN')], null=True),
        ),
    ]
