# Generated by Django 2.2.4 on 2020-05-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_auto_20200512_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assetOther',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='assetSaving',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='assetVehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='liabCards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='liabLoans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='liabOther',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='limitCards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (3, 'LIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
