# Generated by Django 2.2.4 on 2020-05-12 11:21

import apps.lib.site_Enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20200512_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='incomeOther',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='incomeOtherFreq',
            field=models.IntegerField(choices=[(apps.lib.site_Enums.incomeFrequencyEnum(3), 'Wkly'), (apps.lib.site_Enums.incomeFrequencyEnum(2), 'Mth'), (apps.lib.site_Enums.incomeFrequencyEnum(4), 'Qtly'), (apps.lib.site_Enums.incomeFrequencyEnum(5), 'Ann')], default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='incomePension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='incomePensionFreq',
            field=models.IntegerField(choices=[(apps.lib.site_Enums.incomeFrequencyEnum(3), 'Wkly'), (apps.lib.site_Enums.incomeFrequencyEnum(2), 'Mth'), (apps.lib.site_Enums.incomeFrequencyEnum(4), 'Qtly'), (apps.lib.site_Enums.incomeFrequencyEnum(5), 'Ann')], default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='incomeSavings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='incomeSavingsFreq',
            field=models.IntegerField(choices=[(apps.lib.site_Enums.incomeFrequencyEnum(3), 'Wkly'), (apps.lib.site_Enums.incomeFrequencyEnum(2), 'Mth'), (apps.lib.site_Enums.incomeFrequencyEnum(4), 'Qtly'), (apps.lib.site_Enums.incomeFrequencyEnum(5), 'Ann')], default=1),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
