# Generated by Django 2.2.4 on 2020-05-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_auto_20200512_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expenseGroceries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseGroceriesFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=3),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseHomeIns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseHomeInsFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseMedical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseMedicalFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseOther',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseOtherFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseRates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseRatesFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=4),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseRepay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseRepayFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseTransport',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseTransportFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseUtilities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='expenseUtilitiesFreq',
            field=models.IntegerField(choices=[(3, 'W'), (2, 'M'), (4, 'Q'), (5, 'A')], default=4),
        ),
        migrations.AlterField(
            model_name='application',
            name='incomeOtherFreq',
            field=models.IntegerField(choices=[(3, 'W'), (1, 'F'), (2, 'M'), (5, 'A')], default=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='incomePensionFreq',
            field=models.IntegerField(choices=[(3, 'W'), (1, 'F'), (2, 'M'), (5, 'A')], default=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='incomeSavingsFreq',
            field=models.IntegerField(choices=[(3, 'W'), (1, 'F'), (2, 'M'), (5, 'A')], default=2),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN')], null=True),
        ),
    ]
