# Generated by Django 2.2.4 on 2020-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20200513_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='totalAnnualExpenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='totalAnnualIncome',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
