# Generated by Django 2.2.4 on 2020-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20200513_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='expenseGroceriesFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseHomeInsFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseMedicalFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseOtherFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseRatesFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseRepayFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseTransportFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expenseUtilitiesFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='incomeOtherFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='incomePensionFreq',
        ),
        migrations.RemoveField(
            model_name='application',
            name='incomeSavingsFreq',
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseGroceries',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=3),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseHomeIns',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseMedical',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseOther',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseRates',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=4),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseRepay',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseTransport',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='freqExpenseUtilities',
            field=models.IntegerField(choices=[(3, 'Weekly'), (2, 'Monthly'), (4, 'Quarterly'), (5, 'Annually')], default=4),
        ),
        migrations.AddField(
            model_name='application',
            name='freqIncomeOther',
            field=models.IntegerField(choices=[(3, 'Weekly'), (1, 'Fortnightly'), (2, 'Monthly'), (5, 'Annually')], default=2),
        ),
        migrations.AddField(
            model_name='application',
            name='freqIncomePension',
            field=models.IntegerField(choices=[(3, 'Weekly'), (1, 'Fortnightly'), (2, 'Monthly'), (5, 'Annually')], default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='freqIncomeSavings',
            field=models.IntegerField(choices=[(3, 'Weekly'), (1, 'Fortnightly'), (2, 'Monthly'), (5, 'Annually')], default=2),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(6, 'TRANSPORT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT')], null=True),
        ),
    ]
