# Generated by Django 2.2.4 on 2020-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_auto_20200515_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (1, 'INVESTMENT')], null=True),
        ),
    ]
