# Generated by Django 2.2.4 on 2020-05-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20200515_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseGroceries',
            new_name='expenseGroceriesFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseHomeIns',
            new_name='expenseHomeInsFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseMedical',
            new_name='expenseMedicalFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseOther',
            new_name='expenseOtherFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseRates',
            new_name='expenseRatesFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseRepay',
            new_name='expenseRepayFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseTransport',
            new_name='expenseTransportFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqExpenseUtilities',
            new_name='expenseUtilitiesFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqIncomeOther',
            new_name='incomeOtherFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqIncomePension',
            new_name='incomePensionFreq',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='freqIncomeSavings',
            new_name='incomeSavingsFreq',
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS'), (6, 'TRANSPORT')], null=True),
        ),
    ]
