# Generated by Django 2.2.4 on 2020-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_auto_20200515_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='salutation_1',
            field=models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.'), (4, 'Dr.'), (5, 'Prof.')], null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='salutation_2',
            field=models.IntegerField(blank=True, choices=[(1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.'), (4, 'Dr.'), (5, 'Prof.')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT')], null=True),
        ),
    ]
