# Generated by Django 2.2.4 on 2020-05-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_auto_20200516_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bankAccountName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='bankAccountNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='bankBsbNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
