# Generated by Django 2.2.4 on 2020-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_auto_20200516_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='signingName_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='signingName_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='bankAccountNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='bankBsbNumber',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (5, 'CARE'), (3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
