# Generated by Django 2.2.4 on 2020-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20200516_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ip_address',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE'), (3, 'LIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY')], null=True),
        ),
    ]
