# Generated by Django 2.2.4 on 2020-05-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20200522_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(8, 'MORTGAGE'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (6, 'TRANSPORT')], null=True),
        ),
    ]
