# Generated by Django 2.2.4 on 2020-05-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20200527_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(6, 'TRANSPORT'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
