# Generated by Django 2.2.4 on 2020-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_auto_20200527_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='choiceOccupants',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (4, 'GIVE'), (3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (8, 'MORTGAGE')], null=True),
        ),
    ]
