# Generated by Django 2.2.4 on 2020-05-30 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_auto_20200529_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (5, 'CARE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (8, 'MORTGAGE')], null=True),
        ),
        migrations.CreateModel(
            name='ApplicationFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.IntegerField(choices=[(1, 'Rates Notice'), (2, 'Certificate of Insurance'), (100, 'Other')])),
                ('document', models.FileField(max_length=150, upload_to='customerDocuments')),
                ('ip_address', models.CharField(blank=True, max_length=60, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
        ),
    ]
