# Generated by Django 2.2.4 on 2020-05-30 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20200530_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfiles',
            name='documentID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (4, 'GIVE'), (3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (6, 'TRANSPORT')], null=True),
        ),
    ]
