# Generated by Django 2.2.4 on 2020-05-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_auto_20200530_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationFiles',
            new_name='ApplicationDocuments',
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
