# Generated by Django 2.2.4 on 2020-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_auto_20200530_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdocuments',
            old_name='documentID',
            new_name='docUID',
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (6, 'TRANSPORT')], null=True),
        ),
    ]
