# Generated by Django 2.2.4 on 2020-06-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_auto_20200530_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Application'},
        ),
        migrations.AlterModelOptions(
            name='applicationdocuments',
            options={'verbose_name_plural': 'Application Documents'},
        ),
        migrations.AlterField(
            model_name='applicationdocuments',
            name='documentType',
            field=models.IntegerField(choices=[(1, 'Rates Notice'), (2, 'Certificate of Insurance'), (3, 'Stata Levies'), (100, 'Other')]),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (2, 'REFINANCE'), (1, 'TOP_UP'), (5, 'CARE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY')], null=True),
        ),
    ]
