# Generated by Django 2.2.4 on 2020-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_auto_20200601_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (6, 'TRANSPORT')], null=True),
        ),
    ]
