# Generated by Django 2.2.4 on 2020-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_auto_20200601_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicationDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
