# Generated by Django 2.2.4 on 2020-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_auto_20200603_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='choiceIncome',
            new_name='choiceProduct',
        ),
        migrations.AlterField(
            model_name='application',
            name='productType',
            field=models.IntegerField(choices=[(0, 'Multi Purpose'), (1, 'Single Income'), (2, 'Single 20K')], default=0),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (1, 'TOP_UP'), (4, 'GIVE'), (2, 'REFINANCE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (8, 'MORTGAGE')], null=True),
        ),
    ]
