# Generated by Django 2.2.4 on 2020-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_auto_20200605_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='productType',
            field=models.IntegerField(choices=[(0, 'Multi Purpose Lump Sum'), (1, 'Single Income'), (2, 'Single 20K')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(5, 'CARE'), (3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (6, 'TRANSPORT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN')], null=True),
        ),
    ]
