# Generated by Django 2.2.4 on 2020-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_auto_20200608_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (3, 'REGULAR_DRAWDOWN'), (7, 'LUMP_SUM')], null=True),
        ),
    ]
