# Generated by Django 2.2.4 on 2020-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_auto_20200614_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='productType',
            field=models.IntegerField(choices=[(0, 'Lump Sum'), (1, 'Income'), (2, 'Combination'), (3, 'Contingency 20K')], default=0),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM')], null=True),
        ),
    ]
