# Generated by Django 2.2.4 on 2020-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_auto_20200619_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (2, 'REFINANCE'), (3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (6, 'TRANSPORT'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN')], null=True),
        ),
    ]
