# Generated by Django 2.2.4 on 2020-06-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_auto_20200623_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='loanType',
            field=models.IntegerField(choices=[(0, 'Single'), (1, 'Joint')], default=1),
        ),
        migrations.AlterField(
            model_name='applicationdocuments',
            name='documentType',
            field=models.IntegerField(choices=[(1, 'Rates Notice'), (2, 'Insurance Certificate'), (3, 'Strata Levies'), (100, 'Other')]),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (3, 'LIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (6, 'TRANSPORT'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
