# Generated by Django 2.2.4 on 2020-06-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_auto_20200625_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='followUpEmail',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='appStatus',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In-Progress'), (2, 'Expired'), (3, 'Submitted'), (4, 'Contact'), (5, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT'), (1, 'INVESTMENT'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
