# Generated by Django 2.2.4 on 2020-07-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0073_auto_20200706_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE'), (2, 'REFINANCE'), (3, 'LIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(6, 'TRANSPORT'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (2, 'CONTINGENCY'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT')], null=True),
        ),
    ]
