# Generated by Django 2.2.4 on 2020-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_auto_20200717_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (5, 'CARE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (2, 'CONTINGENCY'), (6, 'TRANSPORT'), (8, 'MORTGAGE')], null=True),
        ),
    ]
