# Generated by Django 2.2.4 on 2020-07-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_auto_20200719_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (3, 'LIVE'), (4, 'GIVE'), (1, 'TOP_UP'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (6, 'TRANSPORT'), (8, 'MORTGAGE'), (5, 'RENOVATIONS'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN')], null=True),
        ),
    ]
