# Generated by Django 2.2.4 on 2020-07-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0080_auto_20200719_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'TOP_UP'), (5, 'CARE'), (3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(8, 'MORTGAGE'), (2, 'CONTINGENCY'), (4, 'GIVE_TO_FAMILY'), (7, 'LUMP_SUM'), (5, 'RENOVATIONS'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT'), (6, 'TRANSPORT')], null=True),
        ),
    ]
