# Generated by Django 2.2.4 on 2020-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0082_auto_20200722_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (4, 'GIVE'), (5, 'CARE'), (1, 'TOP_UP'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(2, 'CONTINGENCY'), (6, 'TRANSPORT'), (5, 'RENOVATIONS'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT')], null=True),
        ),
    ]
