# Generated by Django 2.2.4 on 2020-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0086_auto_20200802_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (1, 'TOP_UP'), (2, 'REFINANCE'), (4, 'GIVE'), (5, 'CARE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(8, 'MORTGAGE'), (1, 'INVESTMENT'), (7, 'LUMP_SUM'), (4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (6, 'TRANSPORT_AND_TRAVEL')], null=True),
        ),
    ]
