# Generated by Django 2.2.4 on 2020-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0087_auto_20200813_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(5, 'CARE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(7, 'LUMP_SUM'), (6, 'TRANSPORT_AND_TRAVEL'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS')], null=True),
        ),
    ]
