# Generated by Django 2.2.4 on 2020-08-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0089_auto_20200822_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (5, 'CARE'), (1, 'TOP_UP'), (3, 'LIVE'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (5, 'RENOVATIONS'), (2, 'CONTINGENCY'), (1, 'INVESTMENT'), (4, 'GIVE_TO_FAMILY'), (8, 'MORTGAGE'), (7, 'LUMP_SUM'), (6, 'TRANSPORT_AND_TRAVEL')], null=True),
        ),
    ]
