# Generated by Django 2.2.4 on 2020-09-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0090_auto_20200823_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(2, 'REFINANCE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (4, 'GIVE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(1, 'INVESTMENT'), (8, 'MORTGAGE'), (4, 'GIVE_TO_FAMILY'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (6, 'TRANSPORT_AND_TRAVEL')], null=True),
        ),
    ]
