# Generated by Django 2.2.4 on 2020-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0092_auto_20200902_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (2, 'REFINANCE'), (5, 'CARE'), (4, 'GIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(3, 'REGULAR_DRAWDOWN'), (2, 'CONTINGENCY'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (6, 'TRANSPORT_AND_TRAVEL'), (5, 'RENOVATIONS'), (4, 'GIVE_TO_FAMILY'), (1, 'INVESTMENT')], null=True),
        ),
    ]
