# Generated by Django 2.2.4 on 2020-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0093_auto_20200902_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='customerReports'),
        ),
        migrations.AlterField(
            model_name='application',
            name='productType',
            field=models.IntegerField(choices=[(1, 'Income'), (3, 'Contingency 20K')], default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='summaryDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='customerReports'),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE'), (1, 'TOP_UP'), (3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(5, 'RENOVATIONS'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (4, 'GIVE_TO_FAMILY'), (6, 'TRANSPORT_AND_TRAVEL'), (7, 'LUMP_SUM'), (1, 'INVESTMENT'), (2, 'CONTINGENCY')], null=True),
        ),
    ]
