# Generated by Django 2.2.4 on 2020-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0094_auto_20200911_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpurposes',
            name='category',
            field=models.IntegerField(blank=True, choices=[(3, 'LIVE'), (5, 'CARE'), (2, 'REFINANCE'), (4, 'GIVE'), (1, 'TOP_UP')], null=True),
        ),
        migrations.AlterField(
            model_name='applicationpurposes',
            name='intention',
            field=models.IntegerField(blank=True, choices=[(4, 'GIVE_TO_FAMILY'), (2, 'CONTINGENCY'), (6, 'TRANSPORT_AND_TRAVEL'), (5, 'RENOVATIONS'), (7, 'LUMP_SUM'), (8, 'MORTGAGE'), (3, 'REGULAR_DRAWDOWN'), (1, 'INVESTMENT')], null=True),
        ),
    ]
