# Generated by Django 2.2.4 on 2020-09-26 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enqUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('referrer', models.IntegerField(choices=[(0, 'Phone'), (1, 'Email'), (3, 'Web'), (6, 'Social'), (2, 'Calculator'), (5, 'Partner'), (4, 'Broker'), (7, 'Adviser'), (100, 'Other')])),
                ('referrerID', models.CharField(blank=True, max_length=200, null=True)),
                ('sfLeadID', models.CharField(blank=True, max_length=20, null=True)),
                ('marketingSource', models.IntegerField(blank=True, choices=[(11, 'Web search'), (1, 'TV Advert'), (2, 'TV Advertorial'), (3, 'Radio'), (4, 'Word of mouth'), (6, 'Competitor'), (7, 'Direct mail'), (12, 'Direct Email'), (8, 'Facebook'), (9, 'LinkedIn'), (10, 'Your Life Choices'), (13, 'Starts at 60'), (14, 'Care About'), (16, 'Broker Referral'), (15, 'Broker Specialist'), (17, 'Financial Adviser'), (18, 'Age Care Adviser'), (100, 'Other')], null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('enquiryNotes', models.TextField(blank=True, null=True)),
                ('productType', models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income'), (2, 'Combination'), (3, 'Contingency 20K')], default=0, null=True)),
                ('loanType', models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Joint')], null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age_1', models.IntegerField(blank=True, null=True)),
                ('age_2', models.IntegerField(blank=True, null=True)),
                ('dwellingType', models.IntegerField(blank=True, choices=[(0, 'House'), (1, 'Apartment')], null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=80, null=True)),
                ('suburb', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.IntegerField(blank=True, choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')], null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('valuation', models.IntegerField(blank=True, null=True)),
                ('isReferPostcode', models.BooleanField(blank=True, null=True)),
                ('referPostcodeStatus', models.BooleanField(blank=True, null=True)),
                ('mortgageDebt', models.IntegerField(blank=True, null=True)),
                ('valuationDocument', models.FileField(blank=True, max_length=150, null=True, upload_to='enquiryReports')),
                ('isRefi', models.BooleanField(blank=True, default=False, null=True)),
                ('isTopUp', models.BooleanField(blank=True, default=False, null=True)),
                ('isLive', models.BooleanField(blank=True, default=False, null=True)),
                ('isGive', models.BooleanField(blank=True, default=False, null=True)),
                ('isCare', models.BooleanField(blank=True, default=False, null=True)),
                ('calcLumpSum', models.IntegerField(blank=True, null=True)),
                ('calcIncome', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('maxLoanAmount', models.IntegerField(blank=True, null=True)),
                ('maxDrawdownAmount', models.IntegerField(blank=True, null=True)),
                ('maxDrawdownMonthly', models.IntegerField(blank=True, null=True)),
                ('maxLVR', models.FloatField(blank=True, null=True)),
                ('errorText', models.CharField(blank=True, max_length=40, null=True)),
                ('summaryDocument', models.FileField(blank=True, null=True, upload_to='enquiryReports')),
                ('actioned', models.IntegerField(blank=True, default=0, null=True)),
                ('isCalendly', models.BooleanField(blank=True, default=False, null=True)),
                ('followUp', models.DateTimeField(blank=True, null=True)),
                ('secondfollowUp', models.DateTimeField(blank=True, null=True)),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('closeReason', models.IntegerField(blank=True, choices=[(16, 'Duplicate'), (1, 'Age Restriction'), (2, 'Postcode Restriction'), (3, 'Below minimum loan amount'), (5, 'Refinance too Large'), (6, 'Short-term / Bridging Requirement'), (7, 'Tenants in common'), (8, 'Unsuitable Property'), (9, 'Unsuitable Purpose'), (10, 'Client Pursuing Alternative'), (11, 'Client went to Competitor'), (14, 'Call only'), (13, 'No further action by client'), (15, 'Does not like Reverse Mortgages'), (14, 'Fees too high'), (12, 'Other')], null=True)),
                ('followUpDate', models.DateField(blank=True, null=True)),
                ('followUpNotes', models.TextField(blank=True, null=True)),
                ('doNotMarket', models.BooleanField(default=False)),
                ('enquiryStage', models.IntegerField(blank=True, choices=[(1, 'General Information'), (2, 'Brochure Sent'), (3, 'Customer Summary Sent'), (4, 'Discovery Meeting'), (5, 'Loan Interview'), (6, 'Live Transfer'), (7, 'Duplicate'), (8, 'Future Call'), (15, 'More time to think'), (9, 'Did not Qualify'), (10, 'Not Proceeding'), (11, 'Follow-up: No Answer'), (12, 'Follow-up: Voicemail'), (13, 'Initial: No Answer'), (14, 'NVN: Email Sent')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('calcTotal', models.IntegerField(blank=True, null=True)),
                ('calcTopUp', models.IntegerField(blank=True, null=True)),
                ('calcRefi', models.IntegerField(blank=True, null=True)),
                ('calcLive', models.IntegerField(blank=True, null=True)),
                ('calcGive', models.IntegerField(blank=True, null=True)),
                ('calcCare', models.IntegerField(blank=True, null=True)),
                ('calcDrawdown', models.IntegerField(blank=True, null=True)),
                ('payIntAmount', models.IntegerField(blank=True, null=True)),
                ('payIntPeriod', models.IntegerField(blank=True, null=True)),
                ('lossNotes', models.TextField(blank=True, null=True)),
                ('referralUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referralUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
