# Generated by Django 2.2 on 2019-04-30 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enqUID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('loanType', models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Joint')], default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('age_1', models.IntegerField(blank=True, null=True)),
                ('age_2', models.IntegerField(blank=True, null=True)),
                ('dwellingType', models.IntegerField(blank=True, choices=[(0, 'House'), (1, 'Apartment')], null=True)),
                ('valuation', models.IntegerField(blank=True, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('maxLoanAmount', models.IntegerField(blank=True, null=True)),
                ('maxLVR', models.FloatField(blank=True, null=True)),
                ('errorText', models.CharField(blank=True, max_length=40, null=True)),
                ('isRefi', models.BooleanField(blank=True, default=False, null=True)),
                ('isTopUp', models.BooleanField(blank=True, default=False, null=True)),
                ('isLive', models.BooleanField(blank=True, default=False, null=True)),
                ('isGive', models.BooleanField(blank=True, default=False, null=True)),
                ('isCare', models.BooleanField(blank=True, default=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referrer', models.IntegerField(choices=[(0, 'Phone'), (1, 'Email'), (3, 'Web'), (4, 'Referral'), (100, 'Other'), (2, 'Calculator')])),
                ('referrerID', models.CharField(blank=True, max_length=200, null=True)),
                ('actioned', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('followUp', models.DateTimeField(blank=True, null=True)),
                ('followUpDate', models.DateField(blank=True, null=True)),
                ('summaryDocument', models.FileField(blank=True, null=True, upload_to='')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('enquiryNotes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
    ]
