# Generated by Django 2.2.4 on 2020-04-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Income')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='loanType',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Joint')], null=True),
        ),
    ]
