# Generated by Django 2.2.4 on 2020-04-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20200427_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='calcDrawdown',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
