# Generated by Django 2.2.4 on 2020-05-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_enquiry_calcdrawdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income')], default=0, null=True),
        ),
    ]
