# Generated by Django 2.1.7 on 2019-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20190609_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='payIntAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='payIntPeriod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
