# Generated by Django 2.2.4 on 2020-05-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20200506_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='callReason',
            field=models.IntegerField(blank=True, choices=[(1, 'New - Basic information'), (2, 'New - Specific need'), (4, 'Wrong number'), (5, 'Nuisance number'), (100, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='marketingSource',
            field=models.IntegerField(blank=True, choices=[(1, 'TV Advert'), (2, 'TV Advertorial'), (3, 'Radio'), (4, 'Word of mouth'), (6, 'Competitor'), (7, 'Direct mail/email'), (8, 'Facebook'), (9, 'LinkedIn'), (10, 'Your Life Choices'), (100, 'OTHER')], null=True),
        ),
    ]
