# Generated by Django 2.2.4 on 2020-12-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20201222_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='propensityCategory',
            field=models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C')], null=True),
        ),
    ]
