# Generated by Django 2.1.7 on 2019-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20190623_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='sfLeadID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
