# Generated by Django 2.2.4 on 2021-01-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20201229_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='base_specificity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='street_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='street_type',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
