# Generated by Django 2.2.4 on 2020-05-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0006_auto_20200526_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='suburb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
