# Generated by Django 2.2.4 on 2021-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20210217_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='requestedCallback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='submissionOrigin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
