# Generated by Django 2.2.4 on 2020-05-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20200527_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='maxDrawdownAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='maxDrawdownMonthly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
