# Generated by Django 2.2.4 on 2021-02-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_case_marketing_campaign'),
        ('enquiry', '0008_auto_20210222_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='case.Case'),
        ),
    ]
