# Generated by Django 2.2.4 on 2020-05-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_auto_20200527_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='closeReason',
            field=models.IntegerField(blank=True, choices=[(1, 'Age Restriction'), (2, 'Postcode Restriction'), (3, 'Below minimum loan amount'), (4, 'Credit History'), (5, 'Mortgage too Large'), (6, 'Short-term / Bridging Requirement'), (7, 'Tenants in common'), (8, 'Unsuitable Property'), (9, 'Unsuitable Purpose'), (10, 'Client Pursuing Alternative'), (11, 'Client went to Competitor'), (13, 'No further action by client'), (14, 'Call only'), (12, 'Other')], null=True),
        ),
    ]
