# Generated by Django 2.2.4 on 2021-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_auto_20210128_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='propensityCategory',
            field=models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], null=True),
        ),
    ]
