# Generated by Django 2.2.4 on 2021-02-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_enquiry_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='sfEnqID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
