# Generated by Django 2.2.4 on 2020-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_auto_20200601_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='callReason',
            field=models.IntegerField(blank=True, choices=[(1, 'New - Basic information'), (2, 'New - Specific need'), (4, 'Wrong number'), (5, 'Nuisance call'), (100, 'Other')], null=True),
        ),
    ]
