# Generated by Django 2.2.4 on 2021-03-15 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0016_auto_20210420_1500'),
        ('enquiry', '0011_auto_20210415_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='case.Case'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sfEnqID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
