# Generated by Django 2.2.4 on 2020-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0012_auto_20200605_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Multi Purpose Lump Sum'), (1, 'Single Income'), (2, 'Single 20K')], default=0, null=True),
        ),
    ]
