# Generated by Django 2.2.4 on 2021-03-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0011_auto_20210415_1431'),
        ('enquiry', '0012_auto_20210315_1629'),
    ]

    operations = [
    ]
