# Generated by Django 2.2.4 on 2020-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0013_auto_20200607_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'NSW'), (1, 'VIC'), (2, 'ACT'), (3, 'QLD'), (4, 'SA'), (5, 'WA'), (6, 'TAS'), (7, 'NT')], null=True),
        ),
    ]
