# Generated by Django 2.2.4 on 2020-06-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0014_auto_20200608_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='marketingSource',
            field=models.IntegerField(blank=True, choices=[(11, 'Web search'), (1, 'TV Advert'), (2, 'TV Advertorial'), (3, 'Radio'), (4, 'Word of mouth'), (6, 'Competitor'), (7, 'Direct mail'), (12, 'Direct Email'), (8, 'Facebook'), (9, 'LinkedIn'), (10, 'Your Life Choices'), (100, 'Other')], null=True),
        ),
    ]
