# Generated by Django 2.2.4 on 2021-03-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0014_auto_20210313_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='origin_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
