# Generated by Django 2.2.4 on 2020-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0015_auto_20200614_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='calcIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='calcLumpSum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='productType',
            field=models.IntegerField(blank=True, choices=[(0, 'Lump Sum'), (1, 'Income'), (2, 'Combination'), (3, 'Contingency 20K')], default=0, null=True),
        ),
    ]
