# Generated by Django 2.2.4 on 2021-03-17 02:29

from django.db import migrations
from apps.lib.site_Utilities import split_name
#from config.celery import app


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Enquiry = apps.get_model("enquiry", "Enquiry")
    db_alias = schema_editor.connection.alias

    enquiries = Enquiry.objects.using(db_alias).all()
    for enquiry in enquiries:
        enquiry.firstname, enquiry.lastname = split_name(enquiry.name)
        enquiry.save(ignore_case_creation=True)
        #app.send_task('Update_SF_Enquiry', kwargs={'enqUID': str(enquiry.enqUID)})


def reverse_func(apps, schema_editor):
    Enquiry = apps.get_model("enquiry", "Enquiry")
    db_alias = schema_editor.connection.alias

    enquiries = Enquiry.objects.using(db_alias).all()
    for enquiry in enquiries:
        enquiry.firstname, enquiry.lastname = None, None
        enquiry.save(ignore_case_creation=True)
        #app.send_task('Update_SF_Enquiry', kwargs={'enqUID': str(enquiry.enqUID)})


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0016_auto_20210317_1326'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
