# Generated by Django 2.2.4 on 2020-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0016_auto_20200616_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='isReferPostcode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='referPostcodeStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
