# Generated by Django 2.2.4 on 2021-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_auto_20210318_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
