# Generated by Django 2.2.4 on 2021-03-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0017_auto_20210317_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='name',
            new_name='DEPRECATED_name',
        ),
    ]
