# Generated by Django 2.2.4 on 2020-07-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0018_auto_20200706_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiryStage',
            field=models.IntegerField(blank=True, choices=[(1, 'General Information'), (2, 'Brochure Sent'), (3, 'Summary Sent'), (4, 'Discover Meeting'), (5, 'Loan Interview'), (6, 'Live Transfer'), (7, 'Duplicate'), (8, 'Future Call'), (9, 'Did not Qualify'), (10, 'Not Proceeding'), (11, 'Follow-up: No Answer'), (12, 'Follow-up: Voicemail'), (13, 'Follow-up: No Answer')], null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='marketingSource',
            field=models.IntegerField(blank=True, choices=[(11, 'Web search'), (1, 'TV Advert'), (2, 'TV Advertorial'), (3, 'Radio'), (4, 'Word of mouth'), (6, 'Competitor'), (7, 'Direct mail'), (12, 'Direct Email'), (8, 'Facebook'), (9, 'LinkedIn'), (10, 'Your Life Choices'), (13, 'Starts at 60'), (14, 'Care About'), (100, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='referrer',
            field=models.IntegerField(choices=[(0, 'Phone'), (1, 'Email'), (3, 'Web'), (4, 'Referral'), (5, 'Partner'), (100, 'Other'), (2, 'Calculator')]),
        ),
    ]
