# Generated by Django 2.2.4 on 2020-07-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0020_auto_20200715_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='closeReason',
            field=models.IntegerField(blank=True, choices=[(1, 'Age Restriction'), (2, 'Postcode Restriction'), (3, 'Below minimum loan amount'), (5, 'Refinance too Large'), (6, 'Short-term / Bridging Requirement'), (7, 'Tenants in common'), (8, 'Unsuitable Property'), (9, 'Unsuitable Purpose'), (10, 'Client Pursuing Alternative'), (11, 'Client went to Competitor'), (14, 'Call only'), (13, 'No further action by client'), (15, 'Does not like Reverse Mortgages'), (14, 'Fees too high'), (12, 'Other')], null=True),
        ),
    ]
