# Generated by Django 2.2.4 on 2020-08-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0022_auto_20200722_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='mortgageDebt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
