# Generated by Django 2.2.4 on 2021-06-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0023_auto_20210604_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='submissionOrigin',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
