# Generated by Django 2.2.4 on 2020-08-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0024_auto_20200822_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='valuationDocument',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to='enquiryReports'),
        ),
    ]
