# Generated by Django 2.2.4 on 2021-06-24 01:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0024_auto_20210621_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='head_doc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
