# Generated by Django 2.2.4 on 2020-09-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0025_enquiry_valuationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='summaryDocument',
            field=models.FileField(blank=True, null=True, upload_to='enquiryReports'),
        ),
    ]
