# Generated by Django 2.2.4 on 2021-09-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0028_auto_20210805_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='marketingSource',
            field=models.IntegerField(blank=True, choices=[(11, 'Web search'), (1, 'TV Advert'), (2, 'TV Advertorial'), (3, 'Radio'), (4, 'Word of mouth'), (6, 'Competitor'), (7, 'Direct mail'), (12, 'Direct Email'), (8, 'Facebook'), (20, 'Facebook Interactive'), (21, 'Facebook Calculator'), (9, 'LinkedIn'), (22, 'Google Ads Mobile'), (10, 'Your Life Choices'), (19, 'National Seniors'), (13, 'Starts at 60'), (14, 'Care About'), (16, 'Broker Referral'), (15, 'Broker Specialist'), (17, 'Financial Adviser'), (18, 'Age Care Adviser'), (23, 'Care About - Calculator LP'), (24, 'Starts at 60 - Calculator LP'), (25, 'Your Life Choices - Calculator LP'), (26, 'Facebook Visa'), (100, 'Other')], null=True),
        ),
    ]
