# Generated by Django 2.2.4 on 2021-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0031_auto_20210908_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='utm_source',
            field=models.CharField(max_length=256, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='utm_medium',
            field=models.CharField(max_length=256, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='utm_campaign',
            field=models.CharField(max_length=256, null=True, blank=True),
        ),
    ]
